/** Canonical site origin — used for absolute OG/Twitter image URLs (required by most crawlers). */
export const SITE_URL = 'https://www.softreetechnology.com'

/** Square OG captures — centered viewport screenshots of each page. */
export const OG_SIZE = 1200

export type OgImageMeta = {
  url: string
  width: number
  height: number
  alt: string
}

export function routeToOgFilename(path: string): string {
  if (!path || path === '/') return 'home'
  return path.replace(/^\//, '').replace(/\//g, '--')
}

/** Page screenshot OG image for a route (generated by `npm run generate:og`). */
export function pageOgImage(path: string, alt = 'Softree Technology'): OgImageMeta {
  const file = routeToOgFilename(path)
  return {
    url: `${SITE_URL}/og/pages/${file}.png`,
    width: OG_SIZE,
    height: OG_SIZE,
    alt,
  }
}

export const DEFAULT_OG_IMAGE = pageOgImage('/', 'Softree Technology')
export const CASE_STUDIES_OG_IMAGE = pageOgImage('/case-studies', 'Softree Technology Case Studies')
export const BLOG_OG_IMAGE = pageOgImage('/blog', 'Softree Technology Blog')

export function ogImages(image: OgImageMeta): NonNullable<import('next').Metadata['openGraph']>['images'] {
  return [image]
}

export function twitterImages(image: OgImageMeta): string[] {
  return [image.url]
}

/** Attach square page-screenshot OG + Twitter images to a metadata object. */
export function applyPageOg(path: string, metadata: import('next').Metadata, alt?: string): import('next').Metadata {
  const og = pageOgImage(path, alt)
  const openGraph =
    metadata.openGraph && typeof metadata.openGraph === 'object' ? metadata.openGraph : {}
  const twitter = metadata.twitter && typeof metadata.twitter === 'object' ? metadata.twitter : {}

  return {
    ...metadata,
    openGraph: {
      ...openGraph,
      images: ogImages(og),
    },
    twitter: {
      card: 'summary_large_image',
      ...twitter,
      images: twitterImages(og),
    },
  }
}
