/**
 * Asset_Manifest for the Kore.ai homepage clone.
 *
 * SOURCE OF TRUTH: scripts/.kore-asset-inventory.json
 *   - generated by scripts/extract-kore-assets.mjs from public/kore-source-sections.html
 *   - this module's leaf values mirror that inventory verbatim
 *
 * Every CDN_Passthrough_Asset URL is preserved byte-for-byte from
 * Source_Document including scheme, host, path, query, fragment, and
 * percent-encoding (Requirement 24.2).
 *
 * Each .riv asset is emitted as a CDN_Passthrough_Asset with an additional
 * `fallback` field referencing a Local_Asset under `/kore/rive/` (Requirement
 * 24.4). The local fallback files are staged under `public/kore/rive/` by
 * `scripts/extract-kore-assets.mjs --download-locals` (task 1.8).
 *
 * REQUIREMENTS COVERED: 24.1, 24.2, 24.3, 24.4, 24.5
 *
 * THIS FILE IS AUTHORED BY `scripts/extract-kore-assets.mjs --emit-ts`.
 * Re-run that command after editing the inventory; do not hand-edit leaves.
 */

export type AssetKind = 'cdn-passthrough' | 'local';

export interface CdnPassthroughAsset {
    readonly kind: 'cdn-passthrough';
    readonly url: `https://cdn.prod.website-files.com/${string}`;
    readonly fallback?: LocalAsset; // for .riv files (Req 24.4)
}

export interface LocalAsset {
    readonly kind: 'local';
    readonly url: `/kore/${string}`;
}

export type AssetRef = CdnPassthroughAsset | LocalAsset;

/**
 * Image-specific extension fields applied to an AssetRef.
 *
 * Modelled as an intersection (`AssetRef & ImageAssetMeta`) because
 * `AssetRef` is a discriminated union and TypeScript cannot `extend` a union
 * directly. The shape matches the design document spec.
 */
export interface ImageAssetMeta {
    readonly width?: number;
    readonly height?: number;
    readonly loading?: 'lazy' | 'eager';
    readonly decoding?: 'async' | 'sync' | 'auto';
    readonly srcset?: string;
    readonly sizes?: string;
    readonly alt: string;
}

export type ImageAssetRef = AssetRef & ImageAssetMeta;

export interface VideoAssetRef {
    readonly src: AssetRef;
    readonly poster?: AssetRef;
    readonly autoplay: boolean;
    readonly loop: boolean;
    readonly muted: boolean;
    readonly playsInline: boolean;
}


export const assets = {
    shared: {
        "6634ed2b0cbd8e31117d2028-check-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/66328e08b165a51c20d712a3/6634ed2b0cbd8e31117d2028_check.svg",
        },
        "6634ed2b94e9a926173e1fe1-check-1-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/66328e08b165a51c20d712a3/6634ed2b94e9a926173e1fe1_check-1.svg",
        },
        "68bee79d5b4de5f66fdbf8fd-favicon-32-png": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68bee79d5b4de5f66fdbf8fd_favicon%2032.png",
        },
        "68bee7a1cd1cebc80f4cfe2f-webclip-png": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68bee7a1cd1cebc80f4cfe2f_webclip.png",
        },
        "6995c91dfd5b7b2c603989c6-3aa20f01a358284b496dcc9bccd47bd0-retail-guide-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6995c91dfd5b7b2c603989c6_3aa20f01a358284b496dcc9bccd47bd0_Retail%20Guide.webp",
        },
        "vovi-starter-9d8b21f567cf-f7c28d5917abe.shared.b740e92fb.min-css": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/css/vovi-starter-9d8b21f567cf-f7c28d5917abe.shared.b740e92fb.min.css",
        },
    },
    navigation: {
        "68c46dcd8e2093861ae743a3-bg-wave-simple-4-1-p-1080-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c46dcd8e2093861ae743a3_bg-wave-simple-4%20(1)-p-1080.webp",
        },
        "68c46dcd8e2093861ae743a3-bg-wave-simple-4-1-p-1600-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c46dcd8e2093861ae743a3_bg-wave-simple-4%20(1)-p-1600.webp",
        },
        "68c46dcd8e2093861ae743a3-bg-wave-simple-4-1-p-2000-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c46dcd8e2093861ae743a3_bg-wave-simple-4%20(1)-p-2000.webp",
        },
        "68c46dcd8e2093861ae743a3-bg-wave-simple-4-1-p-2600-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c46dcd8e2093861ae743a3_bg-wave-simple-4%20(1)-p-2600.webp",
        },
        "68c46dcd8e2093861ae743a3-bg-wave-simple-4-1-p-3200-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c46dcd8e2093861ae743a3_bg-wave-simple-4%20(1)-p-3200.webp",
        },
        "68c46dcd8e2093861ae743a3-bg-wave-simple-4-1-p-500-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c46dcd8e2093861ae743a3_bg-wave-simple-4%20(1)-p-500.webp",
        },
        "68c46dcd8e2093861ae743a3-bg-wave-simple-4-1-p-800-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c46dcd8e2093861ae743a3_bg-wave-simple-4%20(1)-p-800.webp",
        },
        "68c46dcd8e2093861ae743a3-bg-wave-simple-4-1-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c46dcd8e2093861ae743a3_bg-wave-simple-4%20(1).webp",
        },
        "68ff5a01881af38c360f28a3-ai-use-cases-insights-from-ai-s-leading-decision-makers-p-500-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68ff5a01881af38c360f28a3_ai_use_cases_insights_from_ai_s_leading_decision_makers-p-500.webp",
        },
        "68ff5a01881af38c360f28a3-ai-use-cases-insights-from-ai-s-leading-decision-makers-p-800-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68ff5a01881af38c360f28a3_ai_use_cases_insights_from_ai_s_leading_decision_makers-p-800.webp",
        },
        "68ff5a01881af38c360f28a3-ai-use-cases-insights-from-ai-s-leading-decision-makers-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68ff5a01881af38c360f28a3_ai_use_cases_insights_from_ai_s_leading_decision_makers.webp",
        },
        "68ff5ab61fc2800046405d5d-beyond-ai-islands-how-to-fully-build-an-enterwise-wide-ai-workforce-p-500-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68ff5ab61fc2800046405d5d_beyond_ai_islands_how_to_fully_build_an_enterwise_wide_ai_workforce-p-500.webp",
        },
        "68ff5ab61fc2800046405d5d-beyond-ai-islands-how-to-fully-build-an-enterwise-wide-ai-workforce-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68ff5ab61fc2800046405d5d_beyond_ai_islands_how_to_fully_build_an_enterwise_wide_ai_workforce.webp",
        },
        "6900cd6400001f247db03abb-forrester-cx-wave-2024-p-500-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6900cd6400001f247db03abb_forrester%20cx%20wave%202024-p-500.webp",
        },
        "6900cd6400001f247db03abb-forrester-cx-wave-2024-p-800-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6900cd6400001f247db03abb_forrester%20cx%20wave%202024-p-800.webp",
        },
        "6900cd6400001f247db03abb-forrester-cx-wave-2024-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6900cd6400001f247db03abb_forrester%20cx%20wave%202024.webp",
        },
        "6900ce6de331c2b312d89805-artboard-1-copy-316-2x-100-p-500-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6900ce6de331c2b312d89805_Artboard%201%20copy%20316%402x-100-p-500.webp",
        },
        "6900ce6de331c2b312d89805-artboard-1-copy-316-2x-100-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6900ce6de331c2b312d89805_Artboard%201%20copy%20316%402x-100.webp",
        },
        "6900ceea68aa38e8954d07ad-artboard-1-copy-281-2x-100-p-500-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6900ceea68aa38e8954d07ad_Artboard%201%20copy%20281%402x-100-p-500.webp",
        },
        "6900ceea68aa38e8954d07ad-artboard-1-copy-281-2x-100-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6900ceea68aa38e8954d07ad_Artboard%201%20copy%20281%402x-100.webp",
        },
        "69830d53e3656931c47d3225-parallel-agent-processing-jpg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/69830d53e3656931c47d3225_Parallel%20Agent%20Processing.jpg",
        },
        "69830d53e3656931c47d3225-parallel-agent-processing-p-500-jpg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/69830d53e3656931c47d3225_Parallel%20Agent%20Processing-p-500.jpg",
        },
        "698f2aa71b1ff9f5915088de-nav-marketplace-card-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/698f2aa71b1ff9f5915088de_Nav%20Marketplace%20Card.webp",
        },
        "699860d81b1c2ed2d4b5219d-version-four-24-jpg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/699860d81b1c2ed2d4b5219d_version-four-24.jpg",
        },
        "699860d81b1c2ed2d4b5219d-version-four-24-p-500-jpg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/699860d81b1c2ed2d4b5219d_version-four-24-p-500.jpg",
        },
        "69b9570e4da32f5ab25cdad5-from-search-to-action-what-makes-agentic-ai-work-in-practice-p-500-png": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/69b9570e4da32f5ab25cdad5_From%20Search%20to%20Action_%20What%20Makes%20Agentic%20AI%20Work%20in%20Practice-p-500.png",
        },
        "69b9570e4da32f5ab25cdad5-from-search-to-action-what-makes-agentic-ai-work-in-practice-png": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/69b9570e4da32f5ab25cdad5_From%20Search%20to%20Action_%20What%20Makes%20Agentic%20AI%20Work%20in%20Practice.png",
        },
        "69bd3c769f4b41875d8f0277-ccw-event-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/69bd3c769f4b41875d8f0277_CCW%20Event.webp",
        },
        "69c4ff7851594334cc0af967-nav-usecases-library-p-500-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/69c4ff7851594334cc0af967_Nav%20Usecases%20Library-p-500.webp",
        },
        "69c4ff7851594334cc0af967-nav-usecases-library-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/69c4ff7851594334cc0af967_Nav%20Usecases%20Library.webp",
        },
        "6a0732948fbd6c250a0ee418-can-todays-ai-agents-survive-their-own-runtime-p-1080-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/6a0732948fbd6c250a0ee418_can-todays-ai-agents-survive-their-own-runtime-p-1080.webp",
        },
        "6a0732948fbd6c250a0ee418-can-todays-ai-agents-survive-their-own-runtime-p-500-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/6a0732948fbd6c250a0ee418_can-todays-ai-agents-survive-their-own-runtime-p-500.webp",
        },
        "6a0732948fbd6c250a0ee418-can-todays-ai-agents-survive-their-own-runtime-p-800-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/6a0732948fbd6c250a0ee418_can-todays-ai-agents-survive-their-own-runtime-p-800.webp",
        },
        "6a0732948fbd6c250a0ee418-can-todays-ai-agents-survive-their-own-runtime-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/6a0732948fbd6c250a0ee418_can-todays-ai-agents-survive-their-own-runtime.webp",
        },
        "6a073312c2fd95b325d5f241-configured-not-coded-the-engineering-discipline-gap-in-agent-development-p-1080-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/6a073312c2fd95b325d5f241_configured-not-coded-the-engineering-discipline-gap-in-agent-development-p-1080.webp",
        },
        "6a073312c2fd95b325d5f241-configured-not-coded-the-engineering-discipline-gap-in-agent-development-p-500-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/6a073312c2fd95b325d5f241_configured-not-coded-the-engineering-discipline-gap-in-agent-development-p-500.webp",
        },
        "6a073312c2fd95b325d5f241-configured-not-coded-the-engineering-discipline-gap-in-agent-development-p-800-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/6a073312c2fd95b325d5f241_configured-not-coded-the-engineering-discipline-gap-in-agent-development-p-800.webp",
        },
        "6a073312c2fd95b325d5f241-configured-not-coded-the-engineering-discipline-gap-in-agent-development-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/6a073312c2fd95b325d5f241_configured-not-coded-the-engineering-discipline-gap-in-agent-development.webp",
        },
        "6a0dd9b872bd55926f41db60-frame-2147240289-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6a0dd9b872bd55926f41db60_frame_2147240289.webp",
        },
    },
    hero: {
        "6717a0dfaf71071a80dfce8b-68e6057dd670c86ab26c8544-kore-hero-banner-ripple-bg-poster-00001-jpg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b%2F68e6057dd670c86ab26c8544_Kore%20Hero%20Banner%20Ripple%20BG-poster-00001.jpg",
        },
        "6717a0dfaf71071a80dfce8b-68e6057dd670c86ab26c8544-kore-hero-banner-ripple-bg-transcode-mp4": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b%2F68e6057dd670c86ab26c8544_Kore%20Hero%20Banner%20Ripple%20BG-transcode.mp4",
        },
        "6717a0dfaf71071a80dfce8b-68e6057dd670c86ab26c8544-kore-hero-banner-ripple-bg-transcode-webm": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b%2F68e6057dd670c86ab26c8544_Kore%20Hero%20Banner%20Ripple%20BG-transcode.webm",
        },
        "69933a25e901a06cbc06c28b-accelerator-application-riv": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/69933a25e901a06cbc06c28b_Accelerator_application.riv",
            fallback: {
                kind: 'local',
                url: "/kore/rive/69933a25e901a06cbc06c28b-accelerator-application.riv",
            },
        },
        "69942ca43878add673c056c0-pre-built-applications-riv": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/69942ca43878add673c056c0_Pre_built_applications.riv",
            fallback: {
                kind: 'local',
                url: "/kore/rive/69942ca43878add673c056c0-pre-built-applications.riv",
            },
        },
        "69942ca45c9fb7ab98c06f1e-tailored-applications-riv": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/69942ca45c9fb7ab98c06f1e_Tailored_applications.riv",
            fallback: {
                kind: 'local',
                url: "/kore/rive/69942ca45c9fb7ab98c06f1e-tailored-applications.riv",
            },
        },
        "6a05f1194d8f8de6627db138-union-arrow-icon-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6a05f1194d8f8de6627db138_Union%20Arrow%20Icon.svg",
        },
    },
    industryTabs: {
        "68c1998017adc89faa49388c-fshome-avif": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1998017adc89faa49388c_fshome.avif",
        },
        "68c19a3b2513192e19a6dcc2-b2bhome-avif": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c19a3b2513192e19a6dcc2_b2bhome.avif",
        },
        "68c19a3b38b198ea6f222a3f-351a023e6b7126c0fc226cf7c9d3a1df-consumerhome-avif": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c19a3b38b198ea6f222a3f_351a023e6b7126c0fc226cf7c9d3a1df_consumerhome.avif",
        },
        "68c19a3bfda82c7f2e12c79a-healthcarehome-avif": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c19a3bfda82c7f2e12c79a_healthcarehome.avif",
        },
        "68c19a3bfdc0d853dd98ecae-telecomhome-avif": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c19a3bfdc0d853dd98ecae_telecomhome.avif",
        },
        "68c1d169088703c8b81957b2-huntington-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d169088703c8b81957b2_Huntington.svg",
        },
        "68c1d1694dc8d42c1a4d8870-london-stock-exchange-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1694dc8d42c1a4d8870_London%20stock%20exchange.svg",
        },
        "68c1d16962ea60d4dff464a3-mashreq-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d16962ea60d4dff464a3_Mashreq.svg",
        },
        "68c1d169dede6644ae4bbf55-metlife-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d169dede6644ae4bbf55_Metlife.svg",
        },
        "68c1d169e8b76dfa0cd44e5a-deutsche-bank-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d169e8b76dfa0cd44e5a_deutsche%20bank.svg",
        },
        "68c1d16a3fc4d5387dd1d0dd-sabadell-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d16a3fc4d5387dd1d0dd_sabadell.svg",
        },
        "68c1d16a9b88dbc782a95258-morgan-stanly-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d16a9b88dbc782a95258_morgan%20stanly.svg",
        },
        "68c1d16aac459c673700a2bb-assurant-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d16aac459c673700a2bb_Assurant.svg",
        },
        "68c1d16b280cf184acd5e590-aaa-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d16b280cf184acd5e590_AAA.svg",
        },
        "68c1d16b6cd956c92977098e-aegon-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d16b6cd956c92977098e_Aegon.svg",
        },
        "68c1d1850dc563c574ddc3cc-siemens-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1850dc563c574ddc3cc_Siemens.svg",
        },
        "68c1d1858f45b56d7f7e204f-simonmed-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1858f45b56d7f7e204f_Simonmed.svg",
        },
        "68c1d185cc2cec440e4dfb0e-carestream-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d185cc2cec440e4dfb0e_Carestream.svg",
        },
        "68c1d186289223b236d382d2-bon-secours-mercy-health-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d186289223b236d382d2_Bon%20Secours%20Mercy%20Health.svg",
        },
        "68c1d1863eb88cfb34a5e9e9-united-health-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1863eb88cfb34a5e9e9_United%20Health.svg",
        },
        "68c1d1865c5f0a8291a89459-garnet-health-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1865c5f0a8291a89459_Garnet%20Health.svg",
        },
        "68c1d1867de07694ae69d4d2-pfizer-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1867de07694ae69d4d2_Pfizer.svg",
        },
        "68c1d1869c9803fbacc6a8df-lilly-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1869c9803fbacc6a8df_Lilly.svg",
        },
        "68c1d186b30b24a8a960deae-carefirst-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d186b30b24a8a960deae_CareFirst.svg",
        },
        "68c1d186bf94b0a51baa22e9-palomar-health-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d186bf94b0a51baa22e9_Palomar%20Health.svg",
        },
        "68c1d186ec53db2ef3ad8a25-otsuka-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d186ec53db2ef3ad8a25_Otsuka.svg",
        },
        "68c1d18798a6097b80c5b40d-florida-blue-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d18798a6097b80c5b40d_Florida%20Blue.svg",
        },
        "68c1d187b73a21e6d9a15ed5-roche-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d187b73a21e6d9a15ed5_Roche.svg",
        },
        "68c1d187f468feef05f862be-johnson-johnson-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d187f468feef05f862be_Johnson%26Johnson.svg",
        },
        "68c1d1a60dc563c574ddcdb0-thomson-reuters-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1a60dc563c574ddcdb0_Thomson%20Reuters.svg",
        },
        "68c1d1a6d6754df1a384f29f-at-t-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1a6d6754df1a384f29f_AT%26T.svg",
        },
        "68c1d1a7088703c8b8196ed5-frontier-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1a7088703c8b8196ed5_Frontier.svg",
        },
        "68c1d1a724314d377a3debc5-nable-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1a724314d377a3debc5_Nable.svg",
        },
        "68c1d1a725d610c7736dbc19-netapp-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1a725d610c7736dbc19_Netapp.svg",
        },
        "68c1d1a7552ceaa0ab3d0f3d-autodesk-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1a7552ceaa0ab3d0f3d_Autodesk.svg",
        },
        "68c1d1a779541145c7a86f8c-wade-wendy-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1a779541145c7a86f8c_Wade%26Wendy.svg",
        },
        "68c1d1a79c9803fbacc6b5aa-altafiber-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1a79c9803fbacc6b5aa_Altafiber.svg",
        },
        "68c1d1a79cab0f637a1e5c60-deutche-telekom-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1a79cab0f637a1e5c60_Deutche%20Telekom.svg",
        },
        "68c1d1a7cc2cec440e4e0646-ebay-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1a7cc2cec440e4e0646_ebay.svg",
        },
        "68c1d1a882fcfcad876f0ba1-charter-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1a882fcfcad876f0ba1_Charter.svg",
        },
        "68c1d1d4249f4c82ff895a65-bosch-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1d4249f4c82ff895a65_Bosch.svg",
        },
        "68c1d1d50b9a5ce5d8240aba-columbia-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1d50b9a5ce5d8240aba_Columbia.svg",
        },
        "68c1d1d536aa4072ccc75d6d-enbridge-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1d536aa4072ccc75d6d_Enbridge.svg",
        },
        "68c1d1d539323cddc94bdcea-alaska-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1d539323cddc94bdcea_Alaska.svg",
        },
        "68c1d1d53ac70422fa9bcc99-nu-skin-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1d53ac70422fa9bcc99_Nu%20Skin.svg",
        },
        "68c1d1d54d990662d8d2bc96-cocacola-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1d54d990662d8d2bc96_CocaCola.svg",
        },
        "68c1d1d55175ebd3c68e46e5-carrier-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1d55175ebd3c68e46e5_Carrier.svg",
        },
        "68c1d1d565c54e2bc4461686-colgate-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1d565c54e2bc4461686_Colgate.svg",
        },
        "68c1d1d5e6083727c0b05de1-lg-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1d5e6083727c0b05de1_LG.svg",
        },
        "68c1d1ec101ca52c56ccb35e-gainwell-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1ec101ca52c56ccb35e_Gainwell.svg",
        },
        "68c1d1ed0792339a0d62f81d-konecta-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1ed0792339a0d62f81d_Konecta.svg",
        },
        "68c1d1ed25d610c7736dcdd6-capgemini-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1ed25d610c7736dcdd6_Capgemini.svg",
        },
        "68c1d1ed5b1cd10dd8e808bb-ntt-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1ed5b1cd10dd8e808bb_NTT.svg",
        },
        "68c1d1eddfbd288aa4f7f223-teleperformance-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1eddfbd288aa4f7f223_Teleperformance.svg",
        },
        "68c1d1ee31659ce1320cbaf4-nippon-steel-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1ee31659ce1320cbaf4_Nippon%20Steel.svg",
        },
        "68c1d1ee3f9b13078b1bc243-airbus-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1ee3f9b13078b1bc243_Airbus.svg",
        },
        "68c1d1ee5024a2e507c6f9ba-mphasis-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1ee5024a2e507c6f9ba_Mphasis.svg",
        },
        "68c1d1ee9b88dbc782a98925-shell-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1ee9b88dbc782a98925_Shell.svg",
        },
        "68c1d1eeab7a117935edb93f-tata-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1eeab7a117935edb93f_Tata.svg",
        },
        "68c1d1eeac459c673700cd62-equinix-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1eeac459c673700cd62_Equinix.svg",
        },
        "68c1d1eecc2cec440e4e1c67-genpact-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c1d1eecc2cec440e4e1c67_Genpact.svg",
        },
    },
    businessOutcomes: {
        "68949b3904aa5fefbc190747-service-card-image-1-avif": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68949b3904aa5fefbc190747_service%20card%20image-1.avif",
        },
        "68949b3904aa5fefbc190747-service-card-image-1-p-500-avif": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68949b3904aa5fefbc190747_service%20card%20image-1-p-500.avif",
        },
        "68949b39149b1becd3a33fe2-service-card-image-avif": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68949b39149b1becd3a33fe2_service%20card%20image.avif",
        },
        "68949b39149b1becd3a33fe2-service-card-image-p-500-avif": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68949b39149b1becd3a33fe2_service%20card%20image-p-500.avif",
        },
        "68949b3a40a73a7b243deb38-service-card-image-big-avif": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68949b3a40a73a7b243deb38_service%20card%20image%20big.avif",
        },
        "68949b3a40a73a7b243deb38-service-card-image-big-p-500-avif": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68949b3a40a73a7b243deb38_service%20card%20image%20big-p-500.avif",
        },
        "68c2dd3839b35889e23cfc41-ai-for-service-2-riv": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c2dd3839b35889e23cfc41_ai_for_service_2.riv",
            fallback: {
                kind: 'local',
                url: "/kore/rive/68c2dd3839b35889e23cfc41-ai-for-service-2.riv",
            },
        },
        "68c2dd387f7c5231e6430987-ai-for-work-2-riv": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68c2dd387f7c5231e6430987_ai_for_work__2.riv",
            fallback: {
                kind: 'local',
                url: "/kore/rive/68c2dd387f7c5231e6430987-ai-for-work-2.riv",
            },
        },
        "6984d216ea44c496001b166b-tabs-section-bg-p-1080-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6984d216ea44c496001b166b_Tabs-Section-BG-p-1080.webp",
        },
        "6984d216ea44c496001b166b-tabs-section-bg-p-1600-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6984d216ea44c496001b166b_Tabs-Section-BG-p-1600.webp",
        },
        "6984d216ea44c496001b166b-tabs-section-bg-p-2000-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6984d216ea44c496001b166b_Tabs-Section-BG-p-2000.webp",
        },
        "6984d216ea44c496001b166b-tabs-section-bg-p-2600-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6984d216ea44c496001b166b_Tabs-Section-BG-p-2600.webp",
        },
        "6984d216ea44c496001b166b-tabs-section-bg-p-3200-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6984d216ea44c496001b166b_Tabs-Section-BG-p-3200.webp",
        },
        "6984d216ea44c496001b166b-tabs-section-bg-p-500-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6984d216ea44c496001b166b_Tabs-Section-BG-p-500.webp",
        },
        "6984d216ea44c496001b166b-tabs-section-bg-p-800-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6984d216ea44c496001b166b_Tabs-Section-BG-p-800.webp",
        },
        "6984d216ea44c496001b166b-tabs-section-bg-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6984d216ea44c496001b166b_Tabs-Section-BG.webp",
        },
        "69860a42eef109546eda2fed-ai-for-banking-screen-p-500-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/69860a42eef109546eda2fed_AI%20for%20Banking%20Screen-p-500.webp",
        },
        "69860a42eef109546eda2fed-ai-for-banking-screen-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/69860a42eef109546eda2fed_AI%20for%20Banking%20Screen.webp",
        },
        "69860a43383b29c2bdcad64d-0efa01f4fec4684336096ceb5ea54a64-ai-for-healthcare-screen-p-500-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/69860a43383b29c2bdcad64d_0efa01f4fec4684336096ceb5ea54a64_AI%20for%20Healthcare%20Screen-p-500.webp",
        },
        "69860a43383b29c2bdcad64d-0efa01f4fec4684336096ceb5ea54a64-ai-for-healthcare-screen-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/69860a43383b29c2bdcad64d_0efa01f4fec4684336096ceb5ea54a64_AI%20for%20Healthcare%20Screen.webp",
        },
        "69860a4789f184b591855cf0-402637d2792fcaf3a1c9a610d17e428b-ai-for-hr-screen-p-500-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/69860a4789f184b591855cf0_402637d2792fcaf3a1c9a610d17e428b_AI%20for%20HR%20Screen-p-500.webp",
        },
        "69860a4789f184b591855cf0-402637d2792fcaf3a1c9a610d17e428b-ai-for-hr-screen-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/69860a4789f184b591855cf0_402637d2792fcaf3a1c9a610d17e428b_AI%20for%20HR%20Screen.webp",
        },
        "69860a47e352f26b99c42e2b-28b9f03a83f93e5f71015ebfb0d7c2bd-ai-for-recruiting-screen-p-500-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/69860a47e352f26b99c42e2b_28b9f03a83f93e5f71015ebfb0d7c2bd_AI%20for%20Recruiting%20Screen-p-500.webp",
        },
        "69860a47e352f26b99c42e2b-28b9f03a83f93e5f71015ebfb0d7c2bd-ai-for-recruiting-screen-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/69860a47e352f26b99c42e2b_28b9f03a83f93e5f71015ebfb0d7c2bd_AI%20for%20Recruiting%20Screen.webp",
        },
        "69860a48529a45f1c4084731-eeccd0d9ae87ba882f4ca184b420fb3e-ai-for-retail-screen-p-500-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/69860a48529a45f1c4084731_eeccd0d9ae87ba882f4ca184b420fb3e_AI%20for%20Retail%20Screen-p-500.webp",
        },
        "69860a48529a45f1c4084731-eeccd0d9ae87ba882f4ca184b420fb3e-ai-for-retail-screen-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/69860a48529a45f1c4084731_eeccd0d9ae87ba882f4ca184b420fb3e_AI%20for%20Retail%20Screen.webp",
        },
        "69860a49ec663d66128fa180-ai-for-it-screen-p-500-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/69860a49ec663d66128fa180_AI%20for%20IT%20Screen-p-500.webp",
        },
        "69860a49ec663d66128fa180-ai-for-it-screen-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/69860a49ec663d66128fa180_AI%20for%20IT%20Screen.webp",
        },
        "699577a1de080c6b2344bdb0-accelerator-application-tab-riv": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/699577a1de080c6b2344bdb0_Accelerator_application%20Tab.riv",
            fallback: {
                kind: 'local',
                url: "/kore/rive/699577a1de080c6b2344bdb0-accelerator-application-tab.riv",
            },
        },
        "6a0722a3a8cdc722bcdae311-7853f8df3a89d3c9d0e947e01a5fec2c-platform-v2-tabs-tr-bg-p-500-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6a0722a3a8cdc722bcdae311_7853f8df3a89d3c9d0e947e01a5fec2c_platform-v2-tabs-tr-bg-p-500.webp",
        },
        "6a0722a3a8cdc722bcdae311-7853f8df3a89d3c9d0e947e01a5fec2c-platform-v2-tabs-tr-bg-p-800-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6a0722a3a8cdc722bcdae311_7853f8df3a89d3c9d0e947e01a5fec2c_platform-v2-tabs-tr-bg-p-800.webp",
        },
        "6a0722a3a8cdc722bcdae311-7853f8df3a89d3c9d0e947e01a5fec2c-platform-v2-tabs-tr-bg-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6a0722a3a8cdc722bcdae311_7853f8df3a89d3c9d0e947e01a5fec2c_platform-v2-tabs-tr-bg.webp",
        },
        "6a07266c6de5192ce7dd7235-platform-v2-tabs-bl-bg-p-500-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6a07266c6de5192ce7dd7235_platform-v2-tabs-bl-bg-p-500.webp",
        },
        "6a07266c6de5192ce7dd7235-platform-v2-tabs-bl-bg-p-800-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6a07266c6de5192ce7dd7235_platform-v2-tabs-bl-bg-p-800.webp",
        },
        "6a07266c6de5192ce7dd7235-platform-v2-tabs-bl-bg-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6a07266c6de5192ce7dd7235_platform-v2-tabs-bl-bg.webp",
        },
    },
    analystRecognition: {
        "68bee086f44becbcb67f3033-1-p-500-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68bee086f44becbcb67f3033_1-p-500.webp",
        },
        "68bee086f44becbcb67f3033-1-p-800-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68bee086f44becbcb67f3033_1-p-800.webp",
        },
        "68bee086f44becbcb67f3033-1-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68bee086f44becbcb67f3033_1.webp",
        },
        "68dfa2caf94b52cac72bdc38-57f76781c7e10f16d4caffb1b88c236d-kore-ai-named-a-leader-in-the-forrester-wave-cognitive-search-platforms-q4-2025-p-1080-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68dfa2caf94b52cac72bdc38_57f76781c7e10f16d4caffb1b88c236d_Kore_ai%20Named%20a%20Leader%20in%20The%20Forrester%20Wave%20Cognitive%20Search%20Platforms%2C%20Q4%202025-p-1080.webp",
        },
        "68dfa2caf94b52cac72bdc38-57f76781c7e10f16d4caffb1b88c236d-kore-ai-named-a-leader-in-the-forrester-wave-cognitive-search-platforms-q4-2025-p-1600-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68dfa2caf94b52cac72bdc38_57f76781c7e10f16d4caffb1b88c236d_Kore_ai%20Named%20a%20Leader%20in%20The%20Forrester%20Wave%20Cognitive%20Search%20Platforms%2C%20Q4%202025-p-1600.webp",
        },
        "68dfa2caf94b52cac72bdc38-57f76781c7e10f16d4caffb1b88c236d-kore-ai-named-a-leader-in-the-forrester-wave-cognitive-search-platforms-q4-2025-p-500-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68dfa2caf94b52cac72bdc38_57f76781c7e10f16d4caffb1b88c236d_Kore_ai%20Named%20a%20Leader%20in%20The%20Forrester%20Wave%20Cognitive%20Search%20Platforms%2C%20Q4%202025-p-500.webp",
        },
        "68dfa2caf94b52cac72bdc38-57f76781c7e10f16d4caffb1b88c236d-kore-ai-named-a-leader-in-the-forrester-wave-cognitive-search-platforms-q4-2025-p-800-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68dfa2caf94b52cac72bdc38_57f76781c7e10f16d4caffb1b88c236d_Kore_ai%20Named%20a%20Leader%20in%20The%20Forrester%20Wave%20Cognitive%20Search%20Platforms%2C%20Q4%202025-p-800.webp",
        },
        "68dfa2caf94b52cac72bdc38-57f76781c7e10f16d4caffb1b88c236d-kore-ai-named-a-leader-in-the-forrester-wave-cognitive-search-platforms-q4-2025-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68dfa2caf94b52cac72bdc38_57f76781c7e10f16d4caffb1b88c236d_Kore_ai%20Named%20a%20Leader%20in%20The%20Forrester%20Wave%20Cognitive%20Search%20Platforms%2C%20Q4%202025.webp",
        },
        "6937e4946e280b2ba3b9e0fc-figure-1-emerging-market-quadrant-for-ai-knowledge-management-appsgeneral-productivity-p-500-png": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6937e4946e280b2ba3b9e0fc_Figure_1_Emerging_Market_Quadrant_for_AI_Knowledge_Management_AppsGeneral_Productivity-p-500.png",
        },
        "6937e4946e280b2ba3b9e0fc-figure-1-emerging-market-quadrant-for-ai-knowledge-management-appsgeneral-productivity-png": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6937e4946e280b2ba3b9e0fc_Figure_1_Emerging_Market_Quadrant_for_AI_Knowledge_Management_AppsGeneral_Productivity.png",
        },
        "6937e4a862c573f91601d43c-figure-1-emerging-market-quadrant-for-generative-ai-engineering-p-500-png": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6937e4a862c573f91601d43c_Figure_1_Emerging_Market_Quadrant_for_Generative_AI_Engineering-p-500.png",
        },
        "6937e4a862c573f91601d43c-figure-1-emerging-market-quadrant-for-generative-ai-engineering-png": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/6937e4a862c573f91601d43c_Figure_1_Emerging_Market_Quadrant_for_Generative_AI_Engineering.png",
        },
    },
    strategicPartners: {
        "68acb73e632d51db064e1b3b-frame-1984079612-avif": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68acb73e632d51db064e1b3b_Frame%201984079612.avif",
        },
        "68acb73efa1938400f416b0b-frame-1984079611-avif": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68acb73efa1938400f416b0b_Frame%201984079611.avif",
        },
    },
    aiInsights: {
        "68c27b14f28aa19ae7a18ca4-ai-insights-thumbnail-01-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/68c27b14f28aa19ae7a18ca4_AI%20Insights%20Thumbnail%2001.webp",
        },
        "68fa2b1e71584b6d574a1c6e-ai-insights-abstract-07-p-1080-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/68fa2b1e71584b6d574a1c6e_AI%20Insights%20Abstract%2007-p-1080.webp",
        },
        "68fa2b1e71584b6d574a1c6e-ai-insights-abstract-07-p-1600-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/68fa2b1e71584b6d574a1c6e_AI%20Insights%20Abstract%2007-p-1600.webp",
        },
        "68fa2b1e71584b6d574a1c6e-ai-insights-abstract-07-p-500-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/68fa2b1e71584b6d574a1c6e_AI%20Insights%20Abstract%2007-p-500.webp",
        },
        "68fa2b1e71584b6d574a1c6e-ai-insights-abstract-07-p-800-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/68fa2b1e71584b6d574a1c6e_AI%20Insights%20Abstract%2007-p-800.webp",
        },
        "68fa2b1e71584b6d574a1c6e-ai-insights-abstract-07-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/68fa2b1e71584b6d574a1c6e_AI%20Insights%20Abstract%2007.webp",
        },
        "6900c68c16d8a7cd9f3fa6ed-ai-insights-thumbnail-06-p-1080-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/6900c68c16d8a7cd9f3fa6ed_AI%20Insights%20Thumbnail%2006-p-1080.webp",
        },
        "6900c68c16d8a7cd9f3fa6ed-ai-insights-thumbnail-06-p-1600-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/6900c68c16d8a7cd9f3fa6ed_AI%20Insights%20Thumbnail%2006-p-1600.webp",
        },
        "6900c68c16d8a7cd9f3fa6ed-ai-insights-thumbnail-06-p-500-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/6900c68c16d8a7cd9f3fa6ed_AI%20Insights%20Thumbnail%2006-p-500.webp",
        },
        "6900c68c16d8a7cd9f3fa6ed-ai-insights-thumbnail-06-p-800-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/6900c68c16d8a7cd9f3fa6ed_AI%20Insights%20Thumbnail%2006-p-800.webp",
        },
        "6900c68c16d8a7cd9f3fa6ed-ai-insights-thumbnail-06-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/6900c68c16d8a7cd9f3fa6ed_AI%20Insights%20Thumbnail%2006.webp",
        },
        "691463d2d3afc6512828bbda-ai-insights-thumbnail-09-p-1080-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/691463d2d3afc6512828bbda_AI%20Insights%20Thumbnail%2009-p-1080.webp",
        },
        "691463d2d3afc6512828bbda-ai-insights-thumbnail-09-p-1600-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/691463d2d3afc6512828bbda_AI%20Insights%20Thumbnail%2009-p-1600.webp",
        },
        "691463d2d3afc6512828bbda-ai-insights-thumbnail-09-p-500-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/691463d2d3afc6512828bbda_AI%20Insights%20Thumbnail%2009-p-500.webp",
        },
        "691463d2d3afc6512828bbda-ai-insights-thumbnail-09-p-800-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/691463d2d3afc6512828bbda_AI%20Insights%20Thumbnail%2009-p-800.webp",
        },
        "691463d2d3afc6512828bbda-ai-insights-thumbnail-09-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/691463d2d3afc6512828bbda_AI%20Insights%20Thumbnail%2009.webp",
        },
        "6a072ac99e4c9c7cab3defb2-ai-insights-thumbnail-05-p-1080-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/6a072ac99e4c9c7cab3defb2_AI%20Insights%20Thumbnail%2005-p-1080.webp",
        },
        "6a072ac99e4c9c7cab3defb2-ai-insights-thumbnail-05-p-1600-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/6a072ac99e4c9c7cab3defb2_AI%20Insights%20Thumbnail%2005-p-1600.webp",
        },
        "6a072ac99e4c9c7cab3defb2-ai-insights-thumbnail-05-p-500-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/6a072ac99e4c9c7cab3defb2_AI%20Insights%20Thumbnail%2005-p-500.webp",
        },
        "6a072ac99e4c9c7cab3defb2-ai-insights-thumbnail-05-p-800-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/6a072ac99e4c9c7cab3defb2_AI%20Insights%20Thumbnail%2005-p-800.webp",
        },
        "6a072ac99e4c9c7cab3defb2-ai-insights-thumbnail-05-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfcec3/6a072ac99e4c9c7cab3defb2_AI%20Insights%20Thumbnail%2005.webp",
        },
    },
    preFooterCta: {
        "682decdbef429c9ff5b9949c-bg-wave-simple-4-avif": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/682decdbef429c9ff5b9949c_bg-wave-simple-4.avif",
        },
        "682decdbef429c9ff5b9949c-bg-wave-simple-4-p-500-avif": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/682decdbef429c9ff5b9949c_bg-wave-simple-4-p-500.avif",
        },
        "68934634672a08409268f696-bg-wave-simple-4-avif": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68934634672a08409268f696_bg-wave-simple-4.avif",
        },
        "68934634672a08409268f696-bg-wave-simple-4-p-500-avif": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68934634672a08409268f696_bg-wave-simple-4-p-500.avif",
        },
    },
    footer: {
        "68ef6f7e1089f67e31928fc9-square-x-twitter-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68ef6f7e1089f67e31928fc9_square-x-twitter.svg",
        },
        "68ef6f7e22a77b2a1bcdafe4-square-linkedin-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68ef6f7e22a77b2a1bcdafe4_square-linkedin.svg",
        },
        "68ef6f7e872240a4ae91207a-square-youtube-svg": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68ef6f7e872240a4ae91207a_square-youtube.svg",
        },
    },
    modals: {
        "68bedbd0eb9a2b6759187ac5-tech-stack-p-1080-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68bedbd0eb9a2b6759187ac5_Tech%20stack-p-1080.webp",
        },
        "68bedbd0eb9a2b6759187ac5-tech-stack-p-1600-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68bedbd0eb9a2b6759187ac5_Tech%20stack-p-1600.webp",
        },
        "68bedbd0eb9a2b6759187ac5-tech-stack-p-2000-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68bedbd0eb9a2b6759187ac5_Tech%20stack-p-2000.webp",
        },
        "68bedbd0eb9a2b6759187ac5-tech-stack-p-500-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68bedbd0eb9a2b6759187ac5_Tech%20stack-p-500.webp",
        },
        "68bedbd0eb9a2b6759187ac5-tech-stack-p-800-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68bedbd0eb9a2b6759187ac5_Tech%20stack-p-800.webp",
        },
        "68bedbd0eb9a2b6759187ac5-tech-stack-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/68bedbd0eb9a2b6759187ac5_Tech%20stack.webp",
        },
        "698b3841f0a01edefe465a15-kore-ai-marketecture-p-1080-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/698b3841f0a01edefe465a15_Kore_ai%20Marketecture-p-1080.webp",
        },
        "698b3841f0a01edefe465a15-kore-ai-marketecture-p-1600-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/698b3841f0a01edefe465a15_Kore_ai%20Marketecture-p-1600.webp",
        },
        "698b3841f0a01edefe465a15-kore-ai-marketecture-p-2000-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/698b3841f0a01edefe465a15_Kore_ai%20Marketecture-p-2000.webp",
        },
        "698b3841f0a01edefe465a15-kore-ai-marketecture-p-2600-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/698b3841f0a01edefe465a15_Kore_ai%20Marketecture-p-2600.webp",
        },
        "698b3841f0a01edefe465a15-kore-ai-marketecture-p-3200-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/698b3841f0a01edefe465a15_Kore_ai%20Marketecture-p-3200.webp",
        },
        "698b3841f0a01edefe465a15-kore-ai-marketecture-p-500-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/698b3841f0a01edefe465a15_Kore_ai%20Marketecture-p-500.webp",
        },
        "698b3841f0a01edefe465a15-kore-ai-marketecture-p-800-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/698b3841f0a01edefe465a15_Kore_ai%20Marketecture-p-800.webp",
        },
        "698b3841f0a01edefe465a15-kore-ai-marketecture-webp": {
            kind: "cdn-passthrough",
            url: "https://cdn.prod.website-files.com/6717a0dfaf71071a80dfce8b/698b3841f0a01edefe465a15_Kore_ai%20Marketecture.webp",
        },
    },
} as const satisfies Record<string, Record<string, AssetRef>>;
