/**
 * Design_Tokens for the Kore.ai homepage clone.
 *
 * SOURCE OF TRUTH: scripts/.kore-style-inventory.json
 *   - generated by scripts/extract-kore-styles.mjs from public/kore-source-sections.html
 *   - this module's leaf values mirror that inventory verbatim
 *
 * KEY DERIVATION (camelCase → kebab-case for tokens.css parity in task 1.6):
 *   - colors / fonts / easings: semantic camelCase keys
 *     (e.g. `koreBlue` → `--kore-blue`, `silk` → `--silk`)
 *   - all other categories: deterministic encoding of the source value, with a
 *     category-letter prefix to guarantee a valid TS identifier:
 *       prefix + sanitize(value)
 *     where sanitize:
 *       - leading "-"  → "Neg"   (e.g. -9999px  → Neg9999px)
 *       - leading "."  → "Dot"   (e.g. .25rem   → Dot25rem)
 *       - all other "." → "p"    (e.g. 0.75rem  → 0p75rem)
 *       - units kept verbatim    (e.g. 8px stays 8px, 1rem stays 1rem)
 *     prefixes:
 *       fs (fontSizes), w (fontWeights), lh (lineHeights), ls (letterSpacings),
 *       s  (spacing),   r (radii),       d  (durations),   z  (zIndices),
 *       bp (breakpoints)
 *
 * Every record is narrowed with `as const` so call-sites read a string-literal
 * (or numeric-literal) type and never an unconstrained `string | number`. The
 * single `tokens` namespace barrel at the bottom re-exports each record so
 * downstream code can either deep-import (`import { colors } from …`) or
 * namespace-import (`import { tokens } from …`).
 *
 * REQUIREMENTS COVERED: 22.1, 22.2, 22.3, 22.4, 22.5
 */

// ---------------------------------------------------------------------------
// colors  (inventory.colors → 9 leaves)
// ---------------------------------------------------------------------------
export const colors = {
    koreBlue: '#4d65ff',
    koreRed: '#dd4615',
    white: '#fff',
    currentColor: 'currentcolor',
    black70: 'rgba(0, 0, 0, 0.7)',
    black90: 'rgba(0, 0, 0, 0.9)',
    white12: 'rgba(255, 255, 255, 0.12)',
    white20: 'rgba(255, 255, 255, 0.20)',
    transparent: 'transparent',
} as const;

// ---------------------------------------------------------------------------
// fonts  (inventory.fontFamilies → 3 leaves)
// task note: inventory bucket is `fontFamilies`; export name is `fonts`
// ---------------------------------------------------------------------------
export const fonts = {
    inter: 'Inter',
    sansSerif: 'sans-serif',
    sourceCodePro: 'Sourcecodepro',
} as const;

// ---------------------------------------------------------------------------
// fontSizes  (inventory.fontSizes → 17 leaves)
// ---------------------------------------------------------------------------
export const fontSizes = {
    fsNeg0p0002971768202080227rem: '-0.0002971768202080227rem',
    fsNeg0p0026778242677824265rem: '-0.0026778242677824265rem',
    fsDot8125rem: '.8125rem',
    fs0p8rem: '0.8rem',
    fs0p75rem: '0.75rem',
    fs0p825rem: '0.825rem',
    fs0p8508974358974357vw: '0.8508974358974357vw',
    fs0p00019230769230782485rem: '0.00019230769230782485rem',
    fs0p037909407665505324rem: '0.037909407665505324rem',
    fs0rem: '0rem',
    fs1p011441307578009vw: '1.011441307578009vw',
    fs1p111441307578009vw: '1.111441307578009vw',
    fs2p083125rem: '2.083125rem',
    fs2p0069686411149825vw: '2.0069686411149825vw',
    fs4p266666666666667vw: '4.266666666666667vw',
    fs4p2666666666666675vw: '4.2666666666666675vw',
    fs4p2845188284518825vw: '4.2845188284518825vw',
} as const;

// ---------------------------------------------------------------------------
// fontWeights  (inventory.fontWeights → 3 leaves)
// ---------------------------------------------------------------------------
export const fontWeights = {
    w400: '400',
    w500: '500',
    w600: '600',
} as const;

// ---------------------------------------------------------------------------
// lineHeights  (inventory.lineHeights → 4 leaves)
// ---------------------------------------------------------------------------
export const lineHeights = {
    lh1: '1',
    lh1p2: '1.2',
    lh1p25rem: '1.25rem',
    lhNormal: 'normal',
} as const;

// ---------------------------------------------------------------------------
// letterSpacings  (inventory.letterSpacings → 2 leaves)
// ---------------------------------------------------------------------------
export const letterSpacings = {
    lsNegDot01625rem: '-.01625rem',
    lsNeg0p01875rem: '-0.01875rem',
} as const;

// ---------------------------------------------------------------------------
// spacing  (inventory.spacing → 47 leaves)
// ---------------------------------------------------------------------------
export const spacing = {
    sNeg0p35rem: '-0.35rem',
    sNeg5p3rem: '-5.3rem',
    sNeg6p6rem: '-6.6rem',
    sNeg9999px: '-9999px',
    sDot25rem: '.25rem',
    sDot75rem: '.75rem',
    s0: '0',
    s0p3rem: '0.3rem',
    s0p5rem: '0.5rem',
    s0p6rem: '0.6rem',
    s0p8rem: '0.8rem',
    s0p10rem: '0.10rem',
    s0p25rem: '0.25rem',
    s0p75em: '0.75em',
    s0p75rem: '0.75rem',
    s0p725rem: '0.725rem',
    s0px: '0px',
    s0rem: '0rem',
    s1p5rem: '1.5rem',
    s1p25rem: '1.25rem',
    s1p75rem: '1.75rem',
    s1p225rem: '1.225rem',
    s1em: '1em',
    s1px: '1px',
    s1rem: '1rem',
    s2rem: '2rem',
    s3p5rem: '3.5rem',
    s3rem: '3rem',
    s5rem: '5rem',
    s8px: '8px',
    s10px: '10px',
    s20px: '20px',
    s22px: '22px',
    s24px: '24px',
    s50vh: '50vh',
    s95vh: '95vh',
    s100vh: '100vh',
    s101vh: '101vh',
    s101vw: '101vw',
    s120px: '120px',
    s180px: '180px',
    s710px: '710px',
    s776px: '776px',
    s875px: '875px',
    s917px: '917px',
    s957px: '957px',
    s969px: '969px',
} as const;

// ---------------------------------------------------------------------------
// radii  (inventory.radii → 3 leaves)
// ---------------------------------------------------------------------------
export const radii = {
    rDot25rem: '.25rem',
    r0p25rem: '0.25rem',
    r20px: '20px',
} as const;

// ---------------------------------------------------------------------------
// shadows  (inventory.shadows → 0 leaves)
// Source_Document declares no box-shadow values; exported as an empty record
// so downstream `tokens.shadows` is always a valid (though empty) lookup.
// ---------------------------------------------------------------------------
export const shadows = {} as const;

// ---------------------------------------------------------------------------
// durations  (inventory.durations → 34 leaves)
// ---------------------------------------------------------------------------
export const durations = {
    dDot1s: '.1s',
    dDot2s: '.2s',
    dDot3s: '.3s',
    dDot4s: '.4s',
    dDot5s: '.5s',
    dDot6s: '.6s',
    dDot7s: '.7s',
    dDot8s: '.8s',
    dDot9s: '.9s',
    dDot55s: '.55s',
    d0p1s: '0.1s',
    d0p2s: '0.2s',
    d0p3s: '0.3s',
    d0p4s: '0.4s',
    d0p5s: '0.5s',
    d0p6s: '0.6s',
    d0p8s: '0.8s',
    d0p9s: '0.9s',
    d0p35s: '0.35s',
    d0p75s: '0.75s',
    d0s: '0s',
    d1p1s: '1.1s',
    d1p2s: '1.2s',
    d1p3s: '1.3s',
    d1p4s: '1.4s',
    d1p5s: '1.5s',
    d1p6s: '1.6s',
    d1p25s: '1.25s',
    d1s: '1s',
    d2s: '2s',
    d4s: '4s',
    d20s: '20s',
    d40s: '40s',
    d200ms: '200ms',
} as const;

// ---------------------------------------------------------------------------
// easings  (inventory.easings → 8 leaves)
// Semantic keys per design.md so call sites can write `tokens.easings.silk`,
// `tokens.easings.anim`, etc.
// ---------------------------------------------------------------------------
export const easings = {
    // cubic-bezier(.22, .61, .36, 1)  — data-anim entrance
    anim: 'cubic-bezier(.22, .61, .36, 1)',
    // cubic-bezier(0.22, 0.6, 0.36, 1) — variant of `anim` written without
    // leading-zero stripping; preserved verbatim from source for parity.
    animLong: 'cubic-bezier(0.22, 0.6, 0.36, 1)',
    // cubic-bezier(0.165, 0.84, 0.44, 1) — easeOutQuart-ish, used by Lenis
    lenis: 'cubic-bezier(0.165, 0.84, 0.44, 1)',
    // cubic-bezier(0.625, 0.05, 0, 1) — accordion grid + Footer back-to-top
    silk: 'cubic-bezier(0.625, 0.05, 0, 1)',
    ease: 'ease',
    easeIn: 'ease-in',
    easeInOut: 'ease-in-out',
    linear: 'linear',
} as const;

// ---------------------------------------------------------------------------
// zIndices  (inventory.zIndices → 11 leaves, integer literals)
// ---------------------------------------------------------------------------
export const zIndices = {
    zNeg1: -1,
    z1: 1,
    z2: 2,
    z9: 9,
    z10: 10,
    z99: 99,
    z9989: 9989,
    z9998: 9998,
    z9999: 9999,
    z99998: 99998,
    z99999: 99999,
} as const;

// ---------------------------------------------------------------------------
// breakpoints  (inventory.breakpoints → 9 leaves, integer CSS pixels)
// Per design.md "Responsive Breakpoint System" + Req 22.3, the higher-level
// Tailwind v4 mapping (mobilePortrait=360, mobileLandscape=480, tablet=768,
// desktop=992) is added alongside the verbatim source-document values so
// component code can reference either set.
// ---------------------------------------------------------------------------
export const breakpoints = {
    // Verbatim source-document breakpoints (max-width legacy queries)
    bp240: 240,
    bp375: 375,
    bp479: 479,
    bp480: 480,
    bp767: 767,
    bp991: 991,
    bp1440: 1440,
    bp1800: 1800,
    bp3000: 3000,
    // Spec-mandated semantic mapping (Req 22.3)
    mobilePortrait: 360,
    mobileLandscape: 480,
    tablet: 768,
    desktop: 992,
} as const;

// ---------------------------------------------------------------------------
// tokens namespace barrel
// ---------------------------------------------------------------------------
export const tokens = {
    colors,
    fonts,
    fontSizes,
    fontWeights,
    lineHeights,
    letterSpacings,
    spacing,
    radii,
    shadows,
    durations,
    easings,
    zIndices,
    breakpoints,
} as const;

export type Tokens = typeof tokens;
