/* eslint-disable */
/** AUTO-GENERATED by scripts/sync-react-bits.ts — do not edit manually */
import type { ReactBitsCatalogEntry } from './types'

export const REACT_BITS_CATALOG: ReactBitsCatalogEntry[] = [
  {
    "id": "Animations/AnimatedContent",
    "name": "AnimatedContent",
    "category": "Animations",
    "description": "Wrapper that animates any children on scroll or mount with configurable direction, distance, duration, easing and disappear options.",
    "docsUrl": "https://reactbits.dev/animations/animated-content",
    "importPath": "./Animations/AnimatedContent/AnimatedContent",
    "defaultProps": {
      "direction": "vertical",
      "distance": 100,
      "delay": 0,
      "reverse": false,
      "duration": 0.8,
      "ease": "power3.out",
      "initialOpacity": 0,
      "animateOpacity": true,
      "scale": 1,
      "threshold": 0.1,
      "disappearAfter": 0,
      "disappearDuration": 0.5,
      "disappearEase": "power3.in"
    }
  },
  {
    "id": "Animations/Antigravity",
    "name": "Antigravity",
    "category": "Animations",
    "description": "3D antigravity particle field that repels from the cursor with smooth motion.",
    "docsUrl": "https://reactbits.dev/animations/antigravity",
    "importPath": "./Animations/Antigravity/Antigravity",
    "defaultProps": {
      "magnetRadius": 6,
      "ringRadius": 7,
      "waveSpeed": 0.4,
      "waveAmplitude": 1,
      "particleSize": 1.5,
      "lerpSpeed": 0.05,
      "count": 300,
      "color": "#5227FF",
      "autoAnimate": true,
      "particleVariance": 1,
      "rotationSpeed": 0,
      "depthFactor": 1,
      "pulseSpeed": 3,
      "particleShape": "capsule",
      "fieldStrength": 10
    }
  },
  {
    "id": "Animations/BlobCursor",
    "name": "BlobCursor",
    "category": "Animations",
    "description": "Organic blob cursor that smoothly follows the pointer with inertia and elastic morphing.",
    "docsUrl": "https://reactbits.dev/animations/blob-cursor",
    "importPath": "./Animations/BlobCursor/BlobCursor",
    "defaultProps": {
      "blobType": "circle",
      "fillColor": "#5227FF",
      "trailCount": 3,
      "sizes": [
        60,
        125,
        75
      ],
      "innerSizes": [
        20,
        35,
        25
      ],
      "innerColor": "rgba(255,255,255,0.8)",
      "opacities": [
        0.6,
        0.6,
        0.6
      ],
      "shadowColor": "rgba(0,0,0,0.75)",
      "shadowBlur": 5,
      "shadowOffsetX": 10,
      "shadowOffsetY": 10,
      "fastDuration": 0.1,
      "slowDuration": 0.5,
      "zIndex": 100
    }
  },
  {
    "id": "Animations/ClickSpark",
    "name": "ClickSpark",
    "category": "Animations",
    "description": "Creates particle spark bursts at click position.",
    "docsUrl": "https://reactbits.dev/animations/click-spark",
    "importPath": "./Animations/ClickSpark/ClickSpark",
    "defaultProps": {
      "sparkColor": "#ffffff",
      "sparkSize": 10,
      "sparkRadius": 15,
      "sparkCount": 8,
      "duration": 400,
      "extraScale": 1
    }
  },
  {
    "id": "Animations/Crosshair",
    "name": "Crosshair",
    "category": "Animations",
    "description": "Custom crosshair cursor with tracking, and link hover effects.",
    "docsUrl": "https://reactbits.dev/animations/crosshair",
    "importPath": "./Animations/Crosshair/Crosshair",
    "defaultProps": {
      "color": "#ffffff",
      "targeted": true
    }
  },
  {
    "id": "Animations/Cubes",
    "name": "Cubes",
    "category": "Animations",
    "description": "3D rotating cube cluster. Supports auto-rotation or hover interaction.",
    "docsUrl": "https://reactbits.dev/animations/cubes",
    "importPath": "./Animations/Cubes/Cubes",
    "defaultProps": {
      "borderStyle": "2px dashed #B497CF",
      "gridSize": 8,
      "maxAngle": 45,
      "radius": 3,
      "autoAnimate": true,
      "rippleOnClick": true
    }
  },
  {
    "id": "Animations/ElectricBorder",
    "name": "ElectricBorder",
    "category": "Animations",
    "description": "Jittery electric energy border with animated arcs, glow and adjustable intensity.",
    "docsUrl": "https://reactbits.dev/animations/electric-border",
    "importPath": "./Animations/ElectricBorder/ElectricBorder",
    "defaultProps": {
      "example": "card",
      "cardProps": {
        "color": "#7df9ff",
        "speed": 1,
        "chaos": 0.12,
        "borderRadius": 16
      },
      "buttonProps": {
        "color": "#B497CF",
        "speed": 1,
        "chaos": 0.12,
        "borderRadius": 999
      },
      "circleProps": {
        "color": "#7df9ff",
        "speed": 1,
        "chaos": 0.12,
        "borderRadius": 999
      }
    }
  },
  {
    "id": "Animations/FadeContent",
    "name": "FadeContent",
    "category": "Animations",
    "description": "Simple directional fade / slide entrance / exit wrapper with threshold-based activation.",
    "docsUrl": "https://reactbits.dev/animations/fade-content",
    "importPath": "./Animations/FadeContent/FadeContent",
    "defaultProps": {
      "ease": "power2.out",
      "blur": false,
      "delay": 0,
      "duration": 1,
      "threshold": 0.1,
      "initialOpacity": 0,
      "disappearEase": "power2.in",
      "disappearAfter": 0,
      "disappearDuration": 0.5
    }
  },
  {
    "id": "Animations/GhostCursor",
    "name": "GhostCursor",
    "category": "Animations",
    "description": "Semi-transparent ghost cursor that smoothly follows the real cursor with a trailing effect.",
    "docsUrl": "https://reactbits.dev/animations/ghost-cursor",
    "importPath": "./Animations/GhostCursor/GhostCursor",
    "defaultProps": {
      "trailLength": 50,
      "inertia": 0.5,
      "grainIntensity": 0.05,
      "bloomStrength": 0.1,
      "bloomRadius": 1,
      "bloomThreshold": 0.025,
      "brightness": 2,
      "color": "#B497CF",
      "fadeDelayMs": 1000,
      "fadeDurationMs": 1500
    }
  },
  {
    "id": "Animations/GlareHover",
    "name": "GlareHover",
    "category": "Animations",
    "description": "Adds a realistic moving glare highlight on hover over any element.",
    "docsUrl": "https://reactbits.dev/animations/glare-hover",
    "importPath": "./Animations/GlareHover/GlareHover",
    "defaultProps": {
      "glareColor": "#ffffff",
      "glareOpacity": 0.3,
      "glareSize": 300,
      "transitionDuration": 800,
      "playOnce": false
    }
  },
  {
    "id": "Animations/GradualBlur",
    "name": "GradualBlur",
    "category": "Animations",
    "description": "Progressively un-blurs content based on scroll or trigger creating a cinematic reveal.",
    "docsUrl": "https://reactbits.dev/animations/gradual-blur",
    "importPath": "./Animations/GradualBlur/GradualBlur",
    "defaultProps": {
      "position": "bottom",
      "strength": 2,
      "height": "7rem",
      "divCount": 5,
      "curve": "bezier",
      "target": "parent",
      "exponential": true,
      "opacity": 1
    }
  },
  {
    "id": "Animations/ImageTrail",
    "name": "ImageTrail",
    "category": "Animations",
    "description": "Cursor-based image trail with several built-in variants.",
    "docsUrl": "https://reactbits.dev/animations/image-trail",
    "importPath": "./Animations/ImageTrail/ImageTrail",
    "defaultProps": {
      "variant": "1"
    }
  },
  {
    "id": "Animations/LaserFlow",
    "name": "LaserFlow",
    "category": "Animations",
    "description": "Dynamic laser light that flows onto a surface, customizable effect.",
    "docsUrl": "https://reactbits.dev/animations/laser-flow",
    "importPath": "./Animations/LaserFlow/LaserFlow",
    "defaultProps": {
      "selectedExample": "box",
      "color": "#CF9EFF",
      "horizontalSizing": 0.5,
      "verticalSizing": 2,
      "wispDensity": 1,
      "wispSpeed": 15,
      "wispIntensity": 5,
      "flowSpeed": 0.35,
      "flowStrength": 0.25,
      "fogIntensity": 0.45,
      "fogScale": 0.3,
      "fogFallSpeed": 0.6,
      "decay": 1.1,
      "falloffStart": 1.2
    }
  },
  {
    "id": "Animations/LogoLoop",
    "name": "LogoLoop",
    "category": "Animations",
    "description": "Continuously looping marquee of brand or tech logos with seamless repeat and hover pause.",
    "docsUrl": "https://reactbits.dev/animations/logo-loop",
    "importPath": "./Animations/LogoLoop/LogoLoop",
    "defaultProps": {
      "speed": 100,
      "logoHeight": 60,
      "gap": 60,
      "hoverSpeed": 0,
      "fadeOut": true,
      "scaleOnHover": true,
      "direction": "left",
      "useCustomRender": false
    }
  },
  {
    "id": "Animations/MagicRings",
    "name": "MagicRings",
    "category": "Animations",
    "description": "Interactive magic rings effect with customizable parameters.",
    "docsUrl": "https://reactbits.dev/animations/magic-rings",
    "importPath": "./Animations/MagicRings/MagicRings",
    "defaultProps": {
      "color": "#A855F7",
      "colorTwo": "#6366F1",
      "ringCount": 6,
      "speed": 1,
      "attenuation": 10,
      "lineThickness": 2,
      "baseRadius": 0.35,
      "radiusStep": 0.1,
      "scaleRate": 0.1,
      "opacity": 1,
      "blur": 0,
      "noiseAmount": 0.1,
      "rotation": 0,
      "ringGap": 1.5,
      "fadeIn": 0.7,
      "fadeOut": 0.5,
      "followMouse": false,
      "mouseInfluence": 0.2,
      "hoverScale": 1.2,
      "parallax": 0.05,
      "clickBurst": false
    }
  },
  {
    "id": "Animations/Magnet",
    "name": "Magnet",
    "category": "Animations",
    "description": "Elements magnetically ease toward the cursor then settle back with spring physics.",
    "docsUrl": "https://reactbits.dev/animations/magnet",
    "importPath": "./Animations/Magnet/Magnet",
    "defaultProps": {
      "disabled": false,
      "padding": 100,
      "magnetStrength": 2
    }
  },
  {
    "id": "Animations/MagnetLines",
    "name": "MagnetLines",
    "category": "Animations",
    "description": "Animated field lines bend toward the cursor.",
    "docsUrl": "https://reactbits.dev/animations/magnet-lines",
    "importPath": "./Animations/MagnetLines/MagnetLines",
    "defaultProps": {
      "rows": 10,
      "columns": 12,
      "containerSize": "40vmin",
      "lineWidth": "2px",
      "lineHeight": "30px",
      "baseAngle": -10,
      "lineColor": "#efefef"
    }
  },
  {
    "id": "Animations/MetaBalls",
    "name": "MetaBalls",
    "category": "Animations",
    "description": "Liquid metaball blobs that merge and separate with smooth implicit surface animation.",
    "docsUrl": "https://reactbits.dev/animations/meta-balls",
    "importPath": "./Animations/MetaBalls/MetaBalls",
    "defaultProps": {
      "color": "#ffffff",
      "cursorBallColor": "#ffffff",
      "speed": 0.3,
      "animationSize": 30,
      "ballCount": 15,
      "clumpFactor": 1,
      "enableMouseInteraction": true,
      "hoverSmoothness": 0.15,
      "cursorBallSize": 2
    }
  },
  {
    "id": "Animations/MetallicPaint",
    "name": "MetallicPaint",
    "category": "Animations",
    "description": "Liquid metallic paint shader which can be applied to SVG elements.",
    "docsUrl": "https://reactbits.dev/animations/metallic-paint",
    "importPath": "./Animations/MetallicPaint/MetallicPaint",
    "defaultProps": {
      "seed": 42,
      "scale": 4,
      "refraction": 0.01,
      "blur": 0.015,
      "liquid": 0.75,
      "speed": 0.3,
      "brightness": 2,
      "contrast": 0.5,
      "angle": 0,
      "fresnel": 1,
      "lightColor": "#ffffff",
      "darkColor": "#000000",
      "patternSharpness": 1,
      "waveAmplitude": 1,
      "noiseScale": 0.5,
      "chromaticSpread": 2,
      "mouseAnimation": false,
      "distortion": 1,
      "contour": 0.2,
      "tintColor": "#feb3ff"
    }
  },
  {
    "id": "Animations/Noise",
    "name": "Noise",
    "category": "Animations",
    "description": "Animated film grain / noise overlay adding subtle texture and motion.",
    "docsUrl": "https://reactbits.dev/animations/noise",
    "importPath": "./Animations/Noise/Noise",
    "defaultProps": {
      "patternSize": 250,
      "patternScaleX": 2,
      "patternScaleY": 2,
      "patternAlpha": 15
    }
  },
  {
    "id": "Animations/OrbitImages",
    "name": "OrbitImages",
    "category": "Animations",
    "description": "SVG Path customizable orbiting images effect",
    "docsUrl": "https://reactbits.dev/animations/orbit-images",
    "importPath": "./Animations/OrbitImages/OrbitImages",
    "defaultProps": {
      "shape": "ellipse",
      "radiusX": 340,
      "radiusY": 80,
      "radius": 160,
      "rotation": -8,
      "duration": 30,
      "itemSize": 80,
      "direction": "normal",
      "fill": true,
      "showPath": true,
      "paused": false
    }
  },
  {
    "id": "Animations/PixelTrail",
    "name": "PixelTrail",
    "category": "Animations",
    "description": "Pixelated cursor trail emitting fading squares with retro digital feel.",
    "docsUrl": "https://reactbits.dev/animations/pixel-trail",
    "importPath": "./Animations/PixelTrail/PixelTrail",
    "defaultProps": {
      "gridSize": 50,
      "trailSize": 0.1,
      "maxAge": 250,
      "interpolate": 5,
      "color": "#5227FF",
      "gooeyEnabled": true,
      "gooStrength": 2
    }
  },
  {
    "id": "Animations/PixelTransition",
    "name": "PixelTransition",
    "category": "Animations",
    "description": "Pixel dissolve transition for content reveal on hover.",
    "docsUrl": "https://reactbits.dev/animations/pixel-transition",
    "importPath": "./Animations/PixelTransition/PixelTransition",
    "defaultProps": {
      "gridSize": 8,
      "pixelColor": "#ffffff",
      "animationStepDuration": 0.4,
      "once": false
    }
  },
  {
    "id": "Animations/Ribbons",
    "name": "Ribbons",
    "category": "Animations",
    "description": "Flowing responsive ribbons/cursor trail driven by physics and pointer motion.",
    "docsUrl": "https://reactbits.dev/animations/ribbons",
    "importPath": "./Animations/Ribbons/Ribbons",
    "defaultProps": {
      "baseThickness": 30,
      "colors": [
        "#5227FF"
      ],
      "speedMultiplier": 0.5,
      "maxAge": 500,
      "enableFade": false,
      "enableShaderEffect": false
    }
  },
  {
    "id": "Animations/ShapeBlur",
    "name": "ShapeBlur",
    "category": "Animations",
    "description": "Morphing blurred geometric shape. The effect occurs on hover.",
    "docsUrl": "https://reactbits.dev/animations/shape-blur",
    "importPath": "./Animations/ShapeBlur/ShapeBlur",
    "defaultProps": {
      "shapeSize": 1,
      "roundness": 0.5,
      "borderSize": 0.05,
      "circleSize": 0.25,
      "circleEdge": 1
    }
  },
  {
    "id": "Animations/SplashCursor",
    "name": "SplashCursor",
    "category": "Animations",
    "description": "Liquid splash burst at cursor with curling ripples and waves.",
    "docsUrl": "https://reactbits.dev/animations/splash-cursor",
    "importPath": "./Animations/SplashCursor/SplashCursor",
    "defaultProps": {
      "DENSITY_DISSIPATION": 3.5,
      "VELOCITY_DISSIPATION": 2,
      "PRESSURE": 0.1,
      "CURL": 3,
      "SPLAT_RADIUS": 0.2,
      "SPLAT_FORCE": 6000,
      "COLOR_UPDATE_SPEED": 10,
      "SHADING": true,
      "RAINBOW_MODE": false,
      "COLOR": "#A855F7"
    }
  },
  {
    "id": "Animations/StarBorder",
    "name": "StarBorder",
    "category": "Animations",
    "description": "Animated star / sparkle border orbiting content with twinkle pulses.",
    "docsUrl": "https://reactbits.dev/animations/star-border",
    "importPath": "./Animations/StarBorder/StarBorder",
    "defaultProps": {
      "thickness": 1,
      "speed": 5,
      "color": "magenta"
    }
  },
  {
    "id": "Animations/StickerPeel",
    "name": "StickerPeel",
    "category": "Animations",
    "description": "Sticker corner lift + peel interaction using 3D transform and shadow depth.",
    "docsUrl": "https://reactbits.dev/animations/sticker-peel",
    "importPath": "./Animations/StickerPeel/StickerPeel",
    "defaultProps": {
      "rotate": 0,
      "width": 200,
      "peelBackHoverPct": 30,
      "peelBackActivePct": 40,
      "lightingIntensity": 0.1,
      "shadowIntensity": 0.5,
      "peelDirection": 0
    }
  },
  {
    "id": "Animations/Strands",
    "name": "Strands",
    "category": "Animations",
    "description": "Glowing ribbon-like strands that ripple and weave across a transparent canvas.",
    "docsUrl": "https://reactbits.dev/animations/strands",
    "importPath": "./Animations/Strands/Strands",
    "defaultProps": {
      "color1": "#F97316",
      "color2": "#7C3AED",
      "color3": "#06B6D4",
      "count": 3,
      "speed": 0.5,
      "amplitude": 1,
      "waviness": 1,
      "thickness": 0.7,
      "glow": 2.6,
      "taper": 3,
      "spread": 1,
      "hueShift": 0,
      "intensity": 0.6,
      "saturation": 2,
      "opacity": 1,
      "scale": 1.5,
      "glass": false,
      "refraction": 1,
      "dispersion": 1,
      "glassSize": 1
    }
  },
  {
    "id": "Animations/TargetCursor",
    "name": "TargetCursor",
    "category": "Animations",
    "description": "A cursor follow animation with 4 corners that lock onto targets.",
    "docsUrl": "https://reactbits.dev/animations/target-cursor",
    "importPath": "./Animations/TargetCursor/TargetCursor",
    "defaultProps": {
      "spinDuration": 2,
      "hideDefaultCursor": true,
      "hoverDuration": 0.2,
      "parallaxOn": true
    }
  },
  {
    "id": "Backgrounds/Aurora",
    "name": "Aurora",
    "category": "Backgrounds",
    "description": "Flowing aurora gradient background.",
    "docsUrl": "https://reactbits.dev/backgrounds/aurora",
    "importPath": "./Backgrounds/Aurora/Aurora",
    "defaultProps": {
      "color1": "#7cff67",
      "color2": "#B497CF",
      "color3": "#5227FF",
      "speed": 1,
      "blend": 0.5
    }
  },
  {
    "id": "Backgrounds/Balatro",
    "name": "Balatro",
    "category": "Backgrounds",
    "description": "The balatro shader, fully customizalbe and interactive.",
    "docsUrl": "https://reactbits.dev/backgrounds/balatro",
    "importPath": "./Backgrounds/Balatro/Balatro",
    "defaultProps": {
      "color1": "#DE443B",
      "color2": "#006BB4",
      "color3": "#162325",
      "isRotate": false,
      "mouseInteraction": true,
      "pixelFilter": 745
    }
  },
  {
    "id": "Backgrounds/Ballpit",
    "name": "Ballpit",
    "category": "Backgrounds",
    "description": "Physics ball pit simulation with bouncing colorful spheres.",
    "docsUrl": "https://reactbits.dev/backgrounds/ballpit",
    "importPath": "./Backgrounds/Ballpit/Ballpit",
    "defaultProps": {
      "count": 100,
      "gravity": 0.01,
      "friction": 0.9975,
      "wallBounce": 0.95,
      "followCursor": false
    }
  },
  {
    "id": "Backgrounds/Beams",
    "name": "Beams",
    "category": "Backgrounds",
    "description": "Crossing animated ribbons with customizable properties.",
    "docsUrl": "https://reactbits.dev/backgrounds/beams",
    "importPath": "./Backgrounds/Beams/Beams",
    "defaultProps": {
      "beamWidth": 3,
      "beamHeight": 30,
      "beamNumber": 20,
      "lightColor": "#ffffff",
      "speed": 2,
      "noiseIntensity": 1.75,
      "scale": 0.2,
      "rotation": 30
    }
  },
  {
    "id": "Backgrounds/ColorBends",
    "name": "ColorBends",
    "category": "Backgrounds",
    "description": "Vibrant color bends with smooth flowing animation.",
    "docsUrl": "https://reactbits.dev/backgrounds/color-bends",
    "importPath": "./Backgrounds/ColorBends/ColorBends",
    "defaultProps": {
      "rotation": 90,
      "autoRotate": 0,
      "speed": 0.2,
      "scale": 1,
      "frequency": 1,
      "warpStrength": 1,
      "mouseInfluence": 1,
      "parallax": 0.5,
      "noise": 0.15,
      "iterations": 1,
      "intensity": 1.5,
      "bandWidth": 6,
      "color": "#A855F7"
    }
  },
  {
    "id": "Backgrounds/DarkVeil",
    "name": "DarkVeil",
    "category": "Backgrounds",
    "description": "Subtle dark background with a smooth animation and postprocessing.",
    "docsUrl": "https://reactbits.dev/backgrounds/dark-veil",
    "importPath": "./Backgrounds/DarkVeil/DarkVeil",
    "defaultProps": {
      "hueShift": 0,
      "noiseIntensity": 0,
      "scanlineIntensity": 0,
      "speed": 0.5,
      "scanlineFrequency": 0,
      "warpAmount": 0
    }
  },
  {
    "id": "Backgrounds/Dither",
    "name": "Dither",
    "category": "Backgrounds",
    "description": "Retro dithered noise shader background.",
    "docsUrl": "https://reactbits.dev/backgrounds/dither",
    "importPath": "./Backgrounds/Dither/Dither",
    "defaultProps": {
      "waveColor": [
        0.5,
        0.5,
        0.5
      ],
      "mouseRadius": 0.3,
      "colorNum": 4,
      "waveAmplitude": 0.3,
      "waveFrequency": 3,
      "waveSpeed": 0.05,
      "enableMouseInteraction": true,
      "disableAnimation": false
    }
  },
  {
    "id": "Backgrounds/DotField",
    "name": "DotField",
    "category": "Backgrounds",
    "description": "Interactive dot grid with cursor bulge, glow, sparkle, and wave effects.",
    "docsUrl": "https://reactbits.dev/backgrounds/dot-field",
    "importPath": "./Backgrounds/DotField/DotField",
    "defaultProps": {
      "dotRadius": 1.5,
      "dotSpacing": 14,
      "cursorRadius": 500,
      "cursorForce": 0.1,
      "bulgeOnly": true,
      "bulgeStrength": 67,
      "glowRadius": 160,
      "sparkle": false,
      "waveAmplitude": 0,
      "gradientFrom": "#A855F7",
      "gradientTo": "#B497CF",
      "glowColor": "#120F17"
    }
  },
  {
    "id": "Backgrounds/DotGrid",
    "name": "DotGrid",
    "category": "Backgrounds",
    "description": "Animated dot grid with cursor interactions.",
    "docsUrl": "https://reactbits.dev/backgrounds/dot-grid",
    "importPath": "./Backgrounds/DotGrid/DotGrid",
    "defaultProps": {
      "dotSize": 5,
      "gap": 15,
      "baseColor": "#2F293A",
      "activeColor": "#5227FF",
      "proximity": 120,
      "shockRadius": 250,
      "shockStrength": 5,
      "resistance": 750,
      "returnDuration": 1.5
    }
  },
  {
    "id": "Backgrounds/EvilEye",
    "name": "EvilEye",
    "category": "Backgrounds",
    "description": "Procedural evil eye shader with animated iris, slit pupil, and fiery outer glow.",
    "docsUrl": "https://reactbits.dev/backgrounds/evil-eye",
    "importPath": "./Backgrounds/EvilEye/EvilEye",
    "defaultProps": {
      "eyeColor": "#FF6F37",
      "intensity": 1.5,
      "pupilSize": 0.6,
      "irisWidth": 0.25,
      "glowIntensity": 0.35,
      "scale": 0.8,
      "noiseScale": 1,
      "pupilFollow": 1,
      "flameSpeed": 1,
      "backgroundColor": "#120F17"
    }
  },
  {
    "id": "Backgrounds/FaultyTerminal",
    "name": "FaultyTerminal",
    "category": "Backgrounds",
    "description": "Terminal CRT scanline squares effect with flicker + noise.",
    "docsUrl": "https://reactbits.dev/backgrounds/faulty-terminal",
    "importPath": "./Backgrounds/FaultyTerminal/FaultyTerminal",
    "defaultProps": {
      "scale": 1.5,
      "digitSize": 1.2,
      "timeScale": 0.5,
      "scanlineIntensity": 0.5,
      "curvature": 0.1,
      "tint": "#A7EF9E",
      "mouseReact": true,
      "mouseStrength": 0.5,
      "pageLoadAnimation": true,
      "noiseAmp": 1,
      "brightness": 0.6
    }
  },
  {
    "id": "Backgrounds/Ferrofluid",
    "name": "Ferrofluid",
    "category": "Backgrounds",
    "description": "A churning magnetic fluid traced by glowing contour lines, with a cursor magnet.",
    "docsUrl": "https://reactbits.dev/backgrounds/ferrofluid",
    "importPath": "./Backgrounds/Ferrofluid/Ferrofluid",
    "defaultProps": {
      "color1": "#ffffff",
      "color2": "#ffffff",
      "color3": "#ffffff",
      "speed": 0.5,
      "scale": 1.6,
      "turbulence": 1,
      "fluidity": 0.1,
      "rimWidth": 0.2,
      "sharpness": 2.5,
      "shimmer": 1.5,
      "glow": 2,
      "flowDirection": "down",
      "mouseInteraction": true,
      "mouseStrength": 1,
      "mouseRadius": 0.35
    }
  },
  {
    "id": "Backgrounds/FloatingLines",
    "name": "FloatingLines",
    "category": "Backgrounds",
    "description": "3D floating lines that react to cursor movement.",
    "docsUrl": "https://reactbits.dev/backgrounds/floating-lines",
    "importPath": "./Backgrounds/FloatingLines/FloatingLines",
    "defaultProps": {
      "enabledWaves": [
        "top",
        "middle",
        "bottom"
      ],
      "lineCount": 8,
      "lineDistance": 8,
      "animationSpeed": 1,
      "interactive": true,
      "bendRadius": 8,
      "bendStrength": -2,
      "gradientStart": "#e945f5",
      "gradientMid": "#6f6f6f",
      "gradientEnd": "#6a6a6a"
    }
  },
  {
    "id": "Backgrounds/Galaxy",
    "name": "Galaxy",
    "category": "Backgrounds",
    "description": "Parallax realistic starfield with pointer interactions.",
    "docsUrl": "https://reactbits.dev/backgrounds/galaxy",
    "importPath": "./Backgrounds/Galaxy/Galaxy",
    "defaultProps": {
      "density": 1,
      "glowIntensity": 0.3,
      "saturation": 0,
      "hueShift": 140,
      "twinkleIntensity": 0.3,
      "rotationSpeed": 0.1,
      "repulsionStrength": 2,
      "autoCenterRepulsion": 0,
      "starSpeed": 0.5,
      "speed": 1,
      "mouseRepulsion": true,
      "mouseInteraction": true
    }
  },
  {
    "id": "Backgrounds/GradientBlinds",
    "name": "GradientBlinds",
    "category": "Backgrounds",
    "description": "Layered gradient blinds with spotlight and noise distortion.",
    "docsUrl": "https://reactbits.dev/backgrounds/gradient-blinds",
    "importPath": "./Backgrounds/GradientBlinds/GradientBlinds",
    "defaultProps": {
      "color1": "#FF9FFC",
      "color2": "#5227FF",
      "angle": 20,
      "noise": 0.5,
      "blindCount": 16,
      "blindMinWidth": 60,
      "spotlightRadius": 0.5,
      "distortAmount": 0,
      "mouseDampening": 0.15,
      "shineDirection": "left"
    }
  },
  {
    "id": "Backgrounds/Grainient",
    "name": "Grainient",
    "category": "Backgrounds",
    "description": "Grainy gradient swirls with soft wave distortion.",
    "docsUrl": "https://reactbits.dev/backgrounds/grainient",
    "importPath": "./Backgrounds/Grainient/Grainient",
    "defaultProps": {
      "color1": "#FF9FFC",
      "color2": "#5227FF",
      "color3": "#B497CF",
      "timeSpeed": 0.25,
      "colorBalance": 0,
      "warpStrength": 1,
      "warpFrequency": 5,
      "warpSpeed": 2,
      "warpAmplitude": 50,
      "blendAngle": 0,
      "blendSoftness": 0.05,
      "rotationAmount": 500,
      "noiseScale": 2,
      "grainAmount": 0.1,
      "grainScale": 2,
      "grainAnimated": false,
      "contrast": 1.5,
      "gamma": 1,
      "saturation": 1,
      "centerX": 0,
      "centerY": 0,
      "zoom": 0.9
    }
  },
  {
    "id": "Backgrounds/GridDistortion",
    "name": "GridDistortion",
    "category": "Backgrounds",
    "description": "Warped grid mesh distorts smoothly reacting to cursor.",
    "docsUrl": "https://reactbits.dev/backgrounds/grid-distortion",
    "importPath": "./Backgrounds/GridDistortion/GridDistortion",
    "defaultProps": {
      "grid": 10,
      "mouse": 0.25
    }
  },
  {
    "id": "Backgrounds/GridMotion",
    "name": "GridMotion",
    "category": "Backgrounds",
    "description": "Perspective moving grid lines based on cusror position.",
    "docsUrl": "https://reactbits.dev/backgrounds/grid-motion",
    "importPath": "./Backgrounds/GridMotion/GridMotion"
  },
  {
    "id": "Backgrounds/GridScan",
    "name": "GridScan",
    "category": "Backgrounds",
    "description": "Animated grid room 3D scan effect and cool interactions.",
    "docsUrl": "https://reactbits.dev/backgrounds/grid-scan",
    "importPath": "./Backgrounds/GridScan/GridScan",
    "defaultProps": {
      "lineThickness": 1,
      "gridScale": 0.1,
      "lineJitter": 0.1,
      "linesColor": "#2F293A",
      "scanColor": "#FF9FFC",
      "enablePost": true,
      "chromaticAberration": 0.002,
      "noiseIntensity": 0.01,
      "scanGlow": 0.5,
      "scanSoftness": 2,
      "enableWebcam": false,
      "showPreview": false
    }
  },
  {
    "id": "Backgrounds/Hyperspeed",
    "name": "Hyperspeed",
    "category": "Backgrounds",
    "description": "Animated lines continuously moving to simulate hyperspace travel on click hold.",
    "docsUrl": "https://reactbits.dev/backgrounds/hyperspeed",
    "importPath": "./Backgrounds/Hyperspeed/Hyperspeed",
    "defaultProps": {
      "activePreset": "one"
    }
  },
  {
    "id": "Backgrounds/Iridescence",
    "name": "Iridescence",
    "category": "Backgrounds",
    "description": "Slick iridescent shader with shifting waves.",
    "docsUrl": "https://reactbits.dev/backgrounds/iridescence",
    "importPath": "./Backgrounds/Iridescence/Iridescence",
    "defaultProps": {
      "color": [
        0.5,
        0.6,
        0.8
      ],
      "speed": 1,
      "mouseReact": true
    }
  },
  {
    "id": "Backgrounds/LetterGlitch",
    "name": "LetterGlitch",
    "category": "Backgrounds",
    "description": "Matrix style letter animation.",
    "docsUrl": "https://reactbits.dev/backgrounds/letter-glitch",
    "importPath": "./Backgrounds/LetterGlitch/LetterGlitch",
    "defaultProps": {
      "smooth": true,
      "speed": 10,
      "colors": [
        "#2b4539",
        "#61dca3",
        "#61b3dc"
      ],
      "showCenterVignette": true,
      "showOuterVignette": false
    }
  },
  {
    "id": "Backgrounds/Lightfall",
    "name": "Lightfall",
    "category": "Backgrounds",
    "description": "Colorful light streaks raining down a glowing tunnel with a cursor light.",
    "docsUrl": "https://reactbits.dev/backgrounds/lightfall",
    "importPath": "./Backgrounds/Lightfall/Lightfall",
    "defaultProps": {
      "color1": "#A6C8FF",
      "color2": "#5227FF",
      "color3": "#FF9FFC",
      "backgroundColor": "#0A29FF",
      "speed": 0.5,
      "streakCount": 2,
      "streakWidth": 1,
      "streakLength": 1,
      "glow": 1,
      "density": 0.6,
      "twinkle": 1,
      "zoom": 3,
      "backgroundGlow": 0.5,
      "mouseInteraction": true,
      "mouseStrength": 0.5,
      "mouseRadius": 1
    }
  },
  {
    "id": "Backgrounds/Lightning",
    "name": "Lightning",
    "category": "Backgrounds",
    "description": "Procedural lightning bolts with branching and glow flicker.",
    "docsUrl": "https://reactbits.dev/backgrounds/lightning",
    "importPath": "./Backgrounds/Lightning/Lightning",
    "defaultProps": {
      "hue": 260,
      "xOffset": 0,
      "speed": 1,
      "intensity": 1,
      "size": 1
    }
  },
  {
    "id": "Backgrounds/LightPillar",
    "name": "LightPillar",
    "category": "Backgrounds",
    "description": "Vertical pillar of light with glow effects.",
    "docsUrl": "https://reactbits.dev/backgrounds/light-pillar",
    "importPath": "./Backgrounds/LightPillar/LightPillar",
    "defaultProps": {
      "topColor": "#5227FF",
      "bottomColor": "#FF9FFC",
      "intensity": 1,
      "rotationSpeed": 0.3,
      "interactive": false,
      "glowAmount": 0.002,
      "pillarWidth": 3,
      "pillarHeight": 0.4,
      "noiseIntensity": 0.5,
      "mixBlendMode": "screen",
      "pillarRotation": 25,
      "quality": "high"
    }
  },
  {
    "id": "Backgrounds/LightRays",
    "name": "LightRays",
    "category": "Backgrounds",
    "description": "Volumetric light rays/beams with customizable direction.",
    "docsUrl": "https://reactbits.dev/backgrounds/light-rays",
    "importPath": "./Backgrounds/LightRays/LightRays",
    "defaultProps": {
      "raysOrigin": "top-center",
      "raysColor": "#ffffff",
      "raysSpeed": 1,
      "lightSpread": 0.5,
      "rayLength": 3,
      "pulsating": false,
      "fadeDistance": 1,
      "saturation": 1,
      "mouseInfluence": 0.1,
      "noiseAmount": 0,
      "distortion": 0
    }
  },
  {
    "id": "Backgrounds/LineWaves",
    "name": "LineWaves",
    "category": "Backgrounds",
    "description": "Animated line wave pattern with colorful warped distortion.",
    "docsUrl": "https://reactbits.dev/backgrounds/line-waves",
    "importPath": "./Backgrounds/LineWaves/LineWaves",
    "defaultProps": {
      "speed": 0.3,
      "innerLineCount": 32,
      "outerLineCount": 36,
      "warpIntensity": 1,
      "rotation": -45,
      "edgeFadeWidth": 0,
      "colorCycleSpeed": 1,
      "brightness": 0.2,
      "color1": "#ffffff",
      "color2": "#ffffff",
      "color3": "#ffffff",
      "enableMouseInteraction": true,
      "mouseInfluence": 2
    }
  },
  {
    "id": "Backgrounds/LiquidChrome",
    "name": "LiquidChrome",
    "category": "Backgrounds",
    "description": "Liquid metallic chrome shader with flowing reflective surface.",
    "docsUrl": "https://reactbits.dev/backgrounds/liquid-chrome",
    "importPath": "./Backgrounds/LiquidChrome/LiquidChrome",
    "defaultProps": {
      "speed": 0.3,
      "baseColor": [
        0.1,
        0.1,
        0.1
      ],
      "interactive": true,
      "amplitude": 0.3
    }
  },
  {
    "id": "Backgrounds/LiquidEther",
    "name": "LiquidEther",
    "category": "Backgrounds",
    "description": "Interactive liquid shader with flowing distortion and customizable colors.",
    "docsUrl": "https://reactbits.dev/backgrounds/liquid-ether",
    "importPath": "./Backgrounds/LiquidEther/LiquidEther",
    "defaultProps": {
      "color0": "#5227FF",
      "color1": "#FF9FFC",
      "color2": "#B497CF",
      "mouseForce": 20,
      "cursorSize": 100,
      "resolution": 0.5,
      "isViscous": true,
      "viscous": 30,
      "iterationsViscous": 32,
      "iterationsPoisson": 32,
      "isBounce": false,
      "autoDemo": true,
      "autoSpeed": 0.5,
      "autoIntensity": 2.2
    }
  },
  {
    "id": "Backgrounds/Orb",
    "name": "Orb",
    "category": "Backgrounds",
    "description": "Floating energy orb with customizable hover effect.",
    "docsUrl": "https://reactbits.dev/backgrounds/orb",
    "importPath": "./Backgrounds/Orb/Orb",
    "defaultProps": {
      "hue": 0,
      "hoverIntensity": 2,
      "rotateOnHover": true,
      "forceHoverState": false,
      "backgroundColor": "#000000"
    }
  },
  {
    "id": "Backgrounds/Particles",
    "name": "Particles",
    "category": "Backgrounds",
    "description": "Configurable particle system.",
    "docsUrl": "https://reactbits.dev/backgrounds/particles",
    "importPath": "./Backgrounds/Particles/Particles",
    "defaultProps": {
      "colors": "#ffffff",
      "particleCount": 200,
      "particleSpread": 10,
      "speed": 0.1,
      "particleBaseSize": 100,
      "moveParticlesOnHover": true,
      "alphaParticles": false,
      "disableRotation": false,
      "pixelRatio": 1
    }
  },
  {
    "id": "Backgrounds/PixelBlast",
    "name": "PixelBlast",
    "category": "Backgrounds",
    "description": "Exploding pixel particle bursts with optional liquid postprocessing.",
    "docsUrl": "https://reactbits.dev/backgrounds/pixel-blast",
    "importPath": "./Backgrounds/PixelBlast/PixelBlast",
    "defaultProps": {
      "variant": "square",
      "pixelSize": 4,
      "patternScale": 2,
      "patternDensity": 1,
      "pixelSizeJitter": 0,
      "enableRipples": true,
      "liquid": false,
      "speed": 0.5,
      "edgeFade": 0.25,
      "color": "#B497CF"
    }
  },
  {
    "id": "Backgrounds/PixelSnow",
    "name": "PixelSnow",
    "category": "Backgrounds",
    "description": "Falling pixelated snow effect with customizable density and speed.",
    "docsUrl": "https://reactbits.dev/backgrounds/pixel-snow",
    "importPath": "./Backgrounds/PixelSnow/PixelSnow",
    "defaultProps": {
      "color": "#ffffff",
      "flakeSize": 0.01,
      "minFlakeSize": 1.25,
      "pixelResolution": 200,
      "speed": 1.25,
      "depthFade": 8,
      "farPlane": 20,
      "brightness": 1,
      "gamma": 0.4545,
      "density": 0.3,
      "variant": "square",
      "direction": 125
    }
  },
  {
    "id": "Backgrounds/Plasma",
    "name": "Plasma",
    "category": "Backgrounds",
    "description": "Organic plasma gradients swirl + morph with smooth turbulence.",
    "docsUrl": "https://reactbits.dev/backgrounds/plasma",
    "importPath": "./Backgrounds/Plasma/Plasma",
    "defaultProps": {
      "color": "#B497CF",
      "speed": 1,
      "direction": "forward",
      "scale": 1,
      "opacity": 1,
      "mouseInteractive": false
    }
  },
  {
    "id": "Backgrounds/PlasmaWave",
    "name": "PlasmaWave",
    "category": "Backgrounds",
    "description": "Raymarched plasma waves with dual-wave interference and OGL.",
    "docsUrl": "https://reactbits.dev/backgrounds/plasma-wave",
    "importPath": "./Backgrounds/PlasmaWave/PlasmaWave",
    "defaultProps": {
      "color1": "#A855F7",
      "color2": "#06B6D4",
      "speed1": 0.05,
      "speed2": 0.05,
      "focalLength": 0.8,
      "bend1": 1,
      "bend2": 0.5,
      "dir2": 1,
      "rotationDeg": 0
    }
  },
  {
    "id": "Backgrounds/Prism",
    "name": "Prism",
    "category": "Backgrounds",
    "description": "Rotating prism with configurable intensity, size, and colors.",
    "docsUrl": "https://reactbits.dev/backgrounds/prism",
    "importPath": "./Backgrounds/Prism/Prism",
    "defaultProps": {
      "animationType": "rotate",
      "timeScale": 0.5,
      "scale": 3.6,
      "noise": 0,
      "glow": 1,
      "height": 3.5,
      "baseWidth": 5.5,
      "hueShift": 0,
      "colorFrequency": 1
    }
  },
  {
    "id": "Backgrounds/PrismaticBurst",
    "name": "PrismaticBurst",
    "category": "Backgrounds",
    "description": "Burst of light rays with controllable color, distortion, amount.",
    "docsUrl": "https://reactbits.dev/backgrounds/prismatic-burst",
    "importPath": "./Backgrounds/PrismaticBurst/PrismaticBurst",
    "defaultProps": {
      "animationType": "rotate3d",
      "intensity": 2,
      "speed": 0.5,
      "distort": 0,
      "hoverDampness": 0.25,
      "rayCount": 0,
      "color0": "#A855F7",
      "color1": "#7C3AED",
      "color2": "#6366F1"
    }
  },
  {
    "id": "Backgrounds/Radar",
    "name": "Radar",
    "category": "Backgrounds",
    "description": "Radar sweep effect with concentric rings, radial spokes, and a rotating beam.",
    "docsUrl": "https://reactbits.dev/backgrounds/radar",
    "importPath": "./Backgrounds/Radar/Radar",
    "defaultProps": {
      "speed": 1,
      "scale": 0.5,
      "ringCount": 10,
      "spokeCount": 10,
      "ringThickness": 0.05,
      "spokeThickness": 0.01,
      "sweepSpeed": 1,
      "sweepWidth": 2,
      "sweepLobes": 1,
      "color": "#9f29ff",
      "backgroundColor": "#000000",
      "falloff": 2,
      "brightness": 1,
      "enableMouseInteraction": true,
      "mouseInfluence": 0.1
    }
  },
  {
    "id": "Backgrounds/RippleGrid",
    "name": "RippleGrid",
    "category": "Backgrounds",
    "description": "A grid that continuously animates with a ripple effect.",
    "docsUrl": "https://reactbits.dev/backgrounds/ripple-grid",
    "importPath": "./Backgrounds/RippleGrid/RippleGrid",
    "defaultProps": {
      "enableRainbow": false,
      "gridColor": "#5227FF",
      "rippleIntensity": 0.05,
      "gridSize": 10,
      "gridThickness": 15,
      "fadeDistance": 1.5,
      "vignetteStrength": 2,
      "glowIntensity": 0.1,
      "opacity": 1,
      "gridRotation": 0,
      "mouseInteraction": true,
      "mouseInteractionRadius": 0.8
    }
  },
  {
    "id": "Backgrounds/ShapeGrid",
    "name": "ShapeGrid",
    "category": "Backgrounds",
    "description": "Animated grid with shape variants (square, hexagon, circle, triangle) + direction customization.",
    "docsUrl": "https://reactbits.dev/backgrounds/shape-grid",
    "importPath": "./Backgrounds/ShapeGrid/ShapeGrid",
    "defaultProps": {
      "direction": "diagonal",
      "borderColor": "#2F293A",
      "hoverColor": "#222222",
      "size": 40,
      "speed": 0.5,
      "shape": "square",
      "hoverTrailAmount": 0
    }
  },
  {
    "id": "Backgrounds/SideRays",
    "name": "SideRays",
    "category": "Backgrounds",
    "description": "Animated light rays emanating from the side with customizable colors and speed.",
    "docsUrl": "https://reactbits.dev/backgrounds/side-rays",
    "importPath": "./Backgrounds/SideRays/SideRays",
    "defaultProps": {
      "speed": 2.5,
      "rayColor1": "#EAB308",
      "rayColor2": "#96c8ff",
      "intensity": 2,
      "spread": 2,
      "origin": "top-right",
      "tilt": 0,
      "saturation": 1.5,
      "blend": 0.75,
      "falloff": 1.6,
      "opacity": 1
    }
  },
  {
    "id": "Backgrounds/Silk",
    "name": "Silk",
    "category": "Backgrounds",
    "description": "Smooth waves background with soft lighting.",
    "docsUrl": "https://reactbits.dev/backgrounds/silk",
    "importPath": "./Backgrounds/Silk/Silk",
    "defaultProps": {
      "speed": 5,
      "scale": 1,
      "color": "#5227FF",
      "noiseIntensity": 1.5,
      "rotation": 0
    }
  },
  {
    "id": "Backgrounds/SoftAurora",
    "name": "SoftAurora",
    "category": "Backgrounds",
    "description": "Soft aurora borealis shader with 3D Perlin noise and cosine gradient palettes.",
    "docsUrl": "https://reactbits.dev/backgrounds/soft-aurora",
    "importPath": "./Backgrounds/SoftAurora/SoftAurora",
    "defaultProps": {
      "speed": 0.6,
      "scale": 1.5,
      "brightness": 1,
      "color1": "#f7f7f7",
      "color2": "#e100ff",
      "noiseFrequency": 2.5,
      "noiseAmplitude": 1,
      "bandHeight": 0.5,
      "bandSpread": 1,
      "octaveDecay": 0.1,
      "layerOffset": 0,
      "colorSpeed": 1,
      "enableMouseInteraction": true,
      "mouseInfluence": 0.25
    }
  },
  {
    "id": "Backgrounds/Threads",
    "name": "Threads",
    "category": "Backgrounds",
    "description": "Animated pattern of lines forming a fabric-like motion.",
    "docsUrl": "https://reactbits.dev/backgrounds/threads",
    "importPath": "./Backgrounds/Threads/Threads",
    "defaultProps": {
      "amplitude": 1,
      "distance": 0,
      "enableMouseInteraction": true
    }
  },
  {
    "id": "Backgrounds/Waves",
    "name": "Waves",
    "category": "Backgrounds",
    "description": "Layered lines that form smooth wave patterns with animation.",
    "docsUrl": "https://reactbits.dev/backgrounds/waves",
    "importPath": "./Backgrounds/Waves/Waves",
    "defaultProps": {
      "lineColor": "#ffffff",
      "waveSpeedX": 0.0125
    }
  },
  {
    "id": "Components/AnimatedList",
    "name": "AnimatedList",
    "category": "Components",
    "description": "List items enter with staggered motion variants for polished reveals.",
    "docsUrl": "https://reactbits.dev/components/animated-list",
    "importPath": "./Components/AnimatedList/AnimatedList",
    "defaultProps": {
      "showGradients": true,
      "enableArrowNavigation": true,
      "displayScrollbar": true
    }
  },
  {
    "id": "Components/BorderGlow",
    "name": "BorderGlow",
    "category": "Components",
    "description": "Glowing mesh-gradient border that follows cursor direction and intensifies near edges.",
    "docsUrl": "https://reactbits.dev/components/border-glow",
    "importPath": "./Components/BorderGlow/BorderGlow",
    "defaultProps": {
      "edgeSensitivity": 30,
      "glowColor": "40 80 80",
      "backgroundColor": "#120F17",
      "borderRadius": 28,
      "glowRadius": 40,
      "glowIntensity": 1,
      "coneSpread": 25,
      "animated": false
    }
  },
  {
    "id": "Components/BounceCards",
    "name": "BounceCards",
    "category": "Components",
    "description": "Cards bounce that bounce in on mount.",
    "docsUrl": "https://reactbits.dev/components/bounce-cards",
    "importPath": "./Components/BounceCards/BounceCards",
    "defaultProps": {
      "enableHover": false,
      "animationDelay": 1,
      "animationStagger": 0.08
    }
  },
  {
    "id": "Components/BubbleMenu",
    "name": "BubbleMenu",
    "category": "Components",
    "description": "Floating circular expanding menu with staggered item reveal.",
    "docsUrl": "https://reactbits.dev/components/bubble-menu",
    "importPath": "./Components/BubbleMenu/BubbleMenu",
    "defaultProps": {
      "animationEase": "back.out(1.5)",
      "menuBg": "#ffffff",
      "menuContentColor": "#111111",
      "animationDuration": 0.5,
      "staggerDelay": 0.12
    }
  },
  {
    "id": "Components/CardNav",
    "name": "CardNav",
    "category": "Components",
    "description": "Expandable navigation bar with card panels revealing nested links.",
    "docsUrl": "https://reactbits.dev/components/card-nav",
    "importPath": "./Components/CardNav/CardNav",
    "defaultProps": {
      "theme": "light",
      "ease": "power3.out"
    }
  },
  {
    "id": "Components/CardSwap",
    "name": "CardSwap",
    "category": "Components",
    "description": "Cards animate position swapping with smooth layout transitions.",
    "docsUrl": "https://reactbits.dev/components/card-swap",
    "importPath": "./Components/CardSwap/CardSwap",
    "defaultProps": {
      "cardDistance": 60,
      "verticalDistance": 70,
      "delay": 5000,
      "skewAmount": 6,
      "easing": "elastic",
      "pauseOnHover": false
    }
  },
  {
    "id": "Components/Carousel",
    "name": "Carousel",
    "category": "Components",
    "description": "Responsive carousel with touch gestures, looping and transitions.",
    "docsUrl": "https://reactbits.dev/components/carousel",
    "importPath": "./Components/Carousel/Carousel",
    "defaultProps": {
      "baseWidth": 300,
      "autoplay": false,
      "autoplayDelay": 3000,
      "pauseOnHover": false,
      "loop": false,
      "round": false
    }
  },
  {
    "id": "Components/ChromaGrid",
    "name": "ChromaGrid",
    "category": "Components",
    "description": "A responsive grid of grayscale tiles. Hovering the grid reaveals their colors.",
    "docsUrl": "https://reactbits.dev/components/chroma-grid",
    "importPath": "./Components/ChromaGrid/ChromaGrid",
    "defaultProps": {
      "radius": 300,
      "damping": 0.45,
      "fadeOut": 0.6
    }
  },
  {
    "id": "Components/CircularGallery",
    "name": "CircularGallery",
    "category": "Components",
    "description": "Circular orbit gallery rotating images.",
    "docsUrl": "https://reactbits.dev/components/circular-gallery",
    "importPath": "./Components/CircularGallery/CircularGallery",
    "defaultProps": {
      "bend": 1,
      "borderRadius": 0.05,
      "scrollSpeed": 2,
      "scrollEase": 0.05,
      "fontUrl": ""
    }
  },
  {
    "id": "Components/Counter",
    "name": "Counter",
    "category": "Components",
    "description": "Flexible animated counter supporting increments + easing.",
    "docsUrl": "https://reactbits.dev/components/counter",
    "importPath": "./Components/Counter/Counter",
    "defaultProps": {
      "digitPlaceHolders": true,
      "value": 1,
      "fontSize": 80,
      "gap": 10
    }
  },
  {
    "id": "Components/DecayCard",
    "name": "DecayCard",
    "category": "Components",
    "description": "Hover parallax effect that disintegrates the content of a card.",
    "docsUrl": "https://reactbits.dev/components/decay-card",
    "importPath": "./Components/DecayCard/DecayCard",
    "defaultProps": {
      "width": 300,
      "height": 400,
      "baseFrequency": 0.015,
      "numOctaves": 5,
      "seed": 4,
      "maxDisplacement": 400,
      "movementBound": 50
    }
  },
  {
    "id": "Components/Dock",
    "name": "Dock",
    "category": "Components",
    "description": "macOS style magnifying dock with proximity scaling of icons.",
    "docsUrl": "https://reactbits.dev/components/dock",
    "importPath": "./Components/Dock/Dock",
    "defaultProps": {
      "panelHeight": 68,
      "baseItemSize": 50,
      "magnification": 70
    }
  },
  {
    "id": "Components/DomeGallery",
    "name": "DomeGallery",
    "category": "Components",
    "description": "Immersive 3D dome gallery projecting images on a hemispheric surface.",
    "docsUrl": "https://reactbits.dev/components/dome-gallery",
    "importPath": "./Components/DomeGallery/DomeGallery",
    "defaultProps": {
      "fit": 0.8,
      "minRadius": 600,
      "maxVerticalRotationDeg": 0,
      "segments": 34,
      "dragDampening": 2,
      "grayscale": true
    }
  },
  {
    "id": "Components/ElasticSlider",
    "name": "ElasticSlider",
    "category": "Components",
    "description": "Slider handle stretches elastically then snaps with spring physics.",
    "docsUrl": "https://reactbits.dev/components/elastic-slider",
    "importPath": "./Components/ElasticSlider/ElasticSlider",
    "defaultProps": {
      "defaultValue": 50,
      "startingValue": 0,
      "maxValue": 100,
      "isStepped": false,
      "stepSize": 10
    }
  },
  {
    "id": "Components/FlowingMenu",
    "name": "FlowingMenu",
    "category": "Components",
    "description": "Liquid flowing active indicator glides between menu items.",
    "docsUrl": "https://reactbits.dev/components/flowing-menu",
    "importPath": "./Components/FlowingMenu/FlowingMenu",
    "defaultProps": {
      "speed": 15,
      "textColor": "#ffffff",
      "bgColor": "#120F17",
      "marqueeBgColor": "#ffffff",
      "marqueeTextColor": "#120F17",
      "borderColor": "#ffffff"
    }
  },
  {
    "id": "Components/FluidGlass",
    "name": "FluidGlass",
    "category": "Components",
    "description": "Glassmorphism container with animated liquid distortion refraction.",
    "docsUrl": "https://reactbits.dev/components/fluid-glass",
    "importPath": "./Components/FluidGlass/FluidGlass",
    "defaultProps": {
      "mode": "lens",
      "scale": 0.25,
      "ior": 1.15,
      "thickness": 2,
      "transmission": 1,
      "roughness": 0,
      "chromaticAberration": 0.05,
      "anisotropy": 0.01
    }
  },
  {
    "id": "Components/FlyingPosters",
    "name": "FlyingPosters",
    "category": "Components",
    "description": "3D posters rotate on scroll infinitely.",
    "docsUrl": "https://reactbits.dev/components/flying-posters",
    "importPath": "./Components/FlyingPosters/FlyingPosters",
    "defaultProps": {
      "items": [
        "https://picsum.photos/500/500?grayscale",
        "https://picsum.photos/600/600?grayscale",
        "https://picsum.photos/400/400?grayscale"
      ],
      "planeWidth": 320,
      "planeHeight": 320,
      "distortion": 3,
      "scrollEase": 0.01,
      "cameraFov": 45,
      "cameraZ": 20
    }
  },
  {
    "id": "Components/Folder",
    "name": "Folder",
    "category": "Components",
    "description": "Interactive folder opens to reveal nested content smooth motion.",
    "docsUrl": "https://reactbits.dev/components/folder",
    "importPath": "./Components/Folder/Folder",
    "defaultProps": {
      "color": "#5227FF",
      "size": 2
    }
  },
  {
    "id": "Components/GlassIcons",
    "name": "GlassIcons",
    "category": "Components",
    "description": "Icon set styled with frosted glass blur.",
    "docsUrl": "https://reactbits.dev/components/glass-icons",
    "importPath": "./Components/GlassIcons/GlassIcons",
    "defaultProps": {
      "colorful": false
    }
  },
  {
    "id": "Components/GlassSurface",
    "name": "GlassSurface",
    "category": "Components",
    "description": "Advanced Apple-style glass surface with real-time distortion + lighting.",
    "docsUrl": "https://reactbits.dev/components/glass-surface",
    "importPath": "./Components/GlassSurface/GlassSurface",
    "defaultProps": {
      "borderRadius": 50,
      "borderWidth": 0.07,
      "brightness": 50,
      "opacity": 0.93,
      "blur": 11,
      "displace": 0.5,
      "backgroundOpacity": 0.1,
      "saturation": 1,
      "distortionScale": -180,
      "redOffset": 0,
      "greenOffset": 10,
      "blueOffset": 20
    }
  },
  {
    "id": "Components/GooeyNav",
    "name": "GooeyNav",
    "category": "Components",
    "description": "Navigation indicator morphs with gooey blob transitions between items.",
    "docsUrl": "https://reactbits.dev/components/gooey-nav",
    "importPath": "./Components/GooeyNav/GooeyNav",
    "defaultProps": {
      "particleCount": 15,
      "timeVariance": 300,
      "particleR": 100
    }
  },
  {
    "id": "Components/InfiniteMenu",
    "name": "InfiniteMenu",
    "category": "Components",
    "description": "Horizontally looping menu effect that scrolls endlessly with seamless wrap.",
    "docsUrl": "https://reactbits.dev/components/infinite-menu",
    "importPath": "./Components/InfiniteMenu/InfiniteMenu",
    "defaultProps": {
      "scale": 1
    }
  },
  {
    "id": "Components/Lanyard",
    "name": "Lanyard",
    "category": "Components",
    "description": "Swinging 3D lanyard / badge card with realistic inertial motion.",
    "docsUrl": "https://reactbits.dev/components/lanyard",
    "importPath": "./Components/Lanyard/Lanyard",
    "defaultProps": {
      "cameraDistance": 24,
      "stopGravity": false
    }
  },
  {
    "id": "Components/MagicBento",
    "name": "MagicBento",
    "category": "Components",
    "description": "Interactive bento grid tiles expand + animate with various options.",
    "docsUrl": "https://reactbits.dev/components/magic-bento",
    "importPath": "./Components/MagicBento/MagicBento",
    "defaultProps": {
      "enableStars": true,
      "enableSpotlight": true,
      "disableAnimations": false,
      "spotlightRadius": 400,
      "enableTilt": false,
      "clickEffect": true,
      "enableMagnetism": false
    }
  },
  {
    "id": "Components/Masonry",
    "name": "Masonry",
    "category": "Components",
    "description": "Responsive masonry layout with animated reflow + gaps optimization.",
    "docsUrl": "https://reactbits.dev/components/masonry",
    "importPath": "./Components/Masonry/Masonry",
    "defaultProps": {
      "ease": "power3.out",
      "animateFrom": "bottom",
      "duration": 0.6,
      "stagger": 0.05,
      "scaleOnHover": true,
      "blurToFocus": true,
      "colorShiftOnHover": false
    }
  },
  {
    "id": "Components/ModelViewer",
    "name": "ModelViewer",
    "category": "Components",
    "description": "Three.js model viewer with orbit controls and lighting presets.",
    "docsUrl": "https://reactbits.dev/components/model-viewer",
    "importPath": "./Components/ModelViewer/ModelViewer",
    "defaultProps": {
      "selectedModel": "toyCar",
      "modelXOffset": 0.5,
      "modelYOffset": 0,
      "enableMouseParallax": true,
      "enableHoverRotation": true,
      "environmentPreset": "forest",
      "fadeIn": false,
      "autoRotate": false,
      "autoRotateSpeed": 0.35,
      "showScreenshotButton": true
    }
  },
  {
    "id": "Components/PillNav",
    "name": "PillNav",
    "category": "Components",
    "description": "Minimal pill nav with sliding active highlight + smooth easing.",
    "docsUrl": "https://reactbits.dev/components/pill-nav",
    "importPath": "./Components/PillNav/PillNav",
    "defaultProps": {
      "theme": "light",
      "initialLoadAnimation": false
    }
  },
  {
    "id": "Components/PixelCard",
    "name": "PixelCard",
    "category": "Components",
    "description": "Card content revealed through pixel expansion transition.",
    "docsUrl": "https://reactbits.dev/components/pixel-card",
    "importPath": "./Components/PixelCard/PixelCard",
    "defaultProps": {
      "variant": "default"
    }
  },
  {
    "id": "Components/ProfileCard",
    "name": "ProfileCard",
    "category": "Components",
    "description": "Animated profile card glare with 3D hover effect.",
    "docsUrl": "https://reactbits.dev/components/profile-card",
    "importPath": "./Components/ProfileCard/ProfileCard",
    "defaultProps": {
      "showIcon": true,
      "showUserInfo": false,
      "enableMobileTilt": false,
      "showBehindGlow": true,
      "behindGlowColor": "rgba(125, 190, 255, 0.67)",
      "customInnerGradient": "linear-gradient(145deg,#60496e8c 0%,#71C4FF44 100%)"
    }
  },
  {
    "id": "Components/ReflectiveCard",
    "name": "ReflectiveCard",
    "category": "Components",
    "description": "Card with dynamic webcam reflection and glare effects that respond to cursor movement.",
    "docsUrl": "https://reactbits.dev/components/reflective-card",
    "importPath": "./Components/ReflectiveCard/ReflectiveCard",
    "defaultProps": {
      "blurStrength": 12,
      "metalness": 1,
      "roughness": 0.75,
      "displacementStrength": 20,
      "noiseScale": 1,
      "specularConstant": 5,
      "grayscale": 0.15,
      "glassDistortion": 30
    }
  },
  {
    "id": "Components/ScrollStack",
    "name": "ScrollStack",
    "category": "Components",
    "description": "Overlapping card stack reveals on scroll with depth layering.",
    "docsUrl": "https://reactbits.dev/components/scroll-stack",
    "importPath": "./Components/ScrollStack/ScrollStack",
    "defaultProps": {
      "itemDistance": 200,
      "itemStackDistance": 30,
      "baseScale": 0.85,
      "rotationAmount": 0,
      "blurAmount": 0,
      "stackPosition": "20%"
    }
  },
  {
    "id": "Components/SpotlightCard",
    "name": "SpotlightCard",
    "category": "Components",
    "description": "Dynamic spotlight follows cursor casting gradient illumination.",
    "docsUrl": "https://reactbits.dev/components/spotlight-card",
    "importPath": "./Components/SpotlightCard/SpotlightCard",
    "defaultProps": {
      "spotlightColor": "#ffffff40"
    }
  },
  {
    "id": "Components/Stack",
    "name": "Stack",
    "category": "Components",
    "description": "Layered stack with swipe animations, autoplay and smooth transitions.",
    "docsUrl": "https://reactbits.dev/components/stack",
    "importPath": "./Components/Stack/Stack",
    "defaultProps": {
      "randomRotation": false,
      "sensitivity": 200,
      "autoplay": false,
      "autoplayDelay": 3000,
      "pauseOnHover": false
    }
  },
  {
    "id": "Components/StaggeredMenu",
    "name": "StaggeredMenu",
    "category": "Components",
    "description": "Menu with staggered item animations and smooth transitions on open/close.",
    "docsUrl": "https://reactbits.dev/components/staggered-menu",
    "importPath": "./Components/StaggeredMenu/StaggeredMenu",
    "defaultProps": {
      "displaySocials": true,
      "accentColor": "#5227FF",
      "menuButtonColor": "#ffffff",
      "position": "right"
    }
  },
  {
    "id": "Components/Stepper",
    "name": "Stepper",
    "category": "Components",
    "description": "Animated multi-step progress indicator with active state transitions.",
    "docsUrl": "https://reactbits.dev/components/stepper",
    "importPath": "./Components/Stepper/Stepper",
    "defaultProps": {
      "name": "",
      "step": 1,
      "backButtonText": "Previous",
      "nextButtonText": "Next",
      "disableStepIndicators": false
    }
  },
  {
    "id": "Components/TiltedCard",
    "name": "TiltedCard",
    "category": "Components",
    "description": "3D perspective tilt card reacting to pointer.",
    "docsUrl": "https://reactbits.dev/components/tilted-card",
    "importPath": "./Components/TiltedCard/TiltedCard",
    "defaultProps": {
      "rotateAmplitude": 12,
      "scaleOnHover": 1.05,
      "showTooltip": true,
      "displayOverlayContent": true
    }
  },
  {
    "id": "TextAnimations/ASCIIText",
    "name": "ASCIIText",
    "category": "TextAnimations",
    "description": "",
    "docsUrl": "https://reactbits.dev",
    "importPath": "./TextAnimations/ASCIIText/ASCIIText",
    "defaultProps": {
      "text": "Hey!",
      "enableWaves": true,
      "asciiFontSize": 8
    }
  },
  {
    "id": "TextAnimations/BlurText",
    "name": "BlurText",
    "category": "TextAnimations",
    "description": "Text starts blurred then crisply resolves for a soft-focus reveal effect.",
    "docsUrl": "https://reactbits.dev/text-animations/blur-text",
    "importPath": "./TextAnimations/BlurText/BlurText",
    "defaultProps": {
      "text": "Isn't this so cool?!",
      "animateBy": "words",
      "direction": "top",
      "delay": 200
    }
  },
  {
    "id": "TextAnimations/CircularText",
    "name": "CircularText",
    "category": "TextAnimations",
    "description": "Layouts characters around a circle with optional rotation animation.",
    "docsUrl": "https://reactbits.dev/text-animations/circular-text",
    "importPath": "./TextAnimations/CircularText/CircularText",
    "defaultProps": {
      "text": "REACT*BITS*COMPONENTS*",
      "onHover": "speedUp",
      "spinDuration": 20
    }
  },
  {
    "id": "TextAnimations/CountUp",
    "name": "CountUp",
    "category": "TextAnimations",
    "description": "Animated number counter supporting formatting and decimals.",
    "docsUrl": "https://reactbits.dev/text-animations/count-up",
    "importPath": "./TextAnimations/CountUp/CountUp",
    "defaultProps": {
      "from": 0,
      "to": 100,
      "duration": 1,
      "delay": 0,
      "direction": "up",
      "separator": ","
    }
  },
  {
    "id": "TextAnimations/CurvedLoop",
    "name": "CurvedLoop",
    "category": "TextAnimations",
    "description": "Flowing looping text path along a customizable curve with drag interaction.",
    "docsUrl": "https://reactbits.dev/text-animations/curved-loop",
    "importPath": "./TextAnimations/CurvedLoop/CurvedLoop",
    "defaultProps": {
      "marqueeText": "Be ✦ Creative ✦ With ✦ React ✦ Bits ✦",
      "speed": 2,
      "curveAmount": 400,
      "interactive": true
    }
  },
  {
    "id": "TextAnimations/DecryptedText",
    "name": "DecryptedText",
    "category": "TextAnimations",
    "description": "Hacker-style decryption cycling random glyphs until resolving to real text.",
    "docsUrl": "https://reactbits.dev/text-animations/decrypted-text",
    "importPath": "./TextAnimations/DecryptedText/DecryptedText",
    "defaultProps": {
      "speed": 60,
      "maxIterations": 10,
      "sequential": true,
      "useOriginalCharsOnly": false,
      "revealDirection": "start",
      "animateOn": "view",
      "clickMode": "once"
    }
  },
  {
    "id": "TextAnimations/FallingText",
    "name": "FallingText",
    "category": "TextAnimations",
    "description": "Characters fall with gravity + bounce creating a playful entrance.",
    "docsUrl": "https://reactbits.dev/text-animations/falling-text",
    "importPath": "./TextAnimations/FallingText/FallingText",
    "defaultProps": {
      "gravity": 0.56,
      "mouseConstraintStiffness": 0.9,
      "trigger": "hover"
    }
  },
  {
    "id": "TextAnimations/FuzzyText",
    "name": "FuzzyText",
    "category": "TextAnimations",
    "description": "Vibrating fuzzy text with controllable hover intensity.",
    "docsUrl": "https://reactbits.dev/text-animations/fuzzy-text",
    "importPath": "./TextAnimations/FuzzyText/FuzzyText",
    "defaultProps": {
      "baseIntensity": 0.2,
      "hoverIntensity": 0.5,
      "enableHover": true,
      "fuzzRange": 30,
      "fps": 60,
      "direction": "horizontal",
      "transitionDuration": 0,
      "clickEffect": false,
      "glitchMode": false,
      "glitchInterval": 2000,
      "glitchDuration": 200,
      "letterSpacing": 0
    }
  },
  {
    "id": "TextAnimations/GlitchText",
    "name": "GlitchText",
    "category": "TextAnimations",
    "description": "RGB split and distortion glitch effect with jitter effects.",
    "docsUrl": "https://reactbits.dev/text-animations/glitch-text",
    "importPath": "./TextAnimations/GlitchText/GlitchText",
    "defaultProps": {
      "speed": 1,
      "enableShadows": true,
      "enableOnHover": false
    }
  },
  {
    "id": "TextAnimations/GradientText",
    "name": "GradientText",
    "category": "TextAnimations",
    "description": "Animated gradient sweep across live text with speed and color control.",
    "docsUrl": "https://reactbits.dev/text-animations/gradient-text",
    "importPath": "./TextAnimations/GradientText/GradientText",
    "defaultProps": {
      "colors": [
        "#5227FF",
        "#FF9FFC",
        "#B497CF"
      ],
      "animationSpeed": 8,
      "direction": "horizontal",
      "pauseOnHover": false,
      "yoyo": true,
      "showBorder": false
    }
  },
  {
    "id": "TextAnimations/RotatingText",
    "name": "RotatingText",
    "category": "TextAnimations",
    "description": "Cycles through multiple phrases with 3D rotate / flip transitions.",
    "docsUrl": "https://reactbits.dev/text-animations/rotating-text",
    "importPath": "./TextAnimations/RotatingText/RotatingText",
    "defaultProps": {
      "rotationInterval": 2000,
      "staggerDuration": 0.025,
      "staggerFrom": "last",
      "splitBy": "characters",
      "auto": true,
      "loop": true
    }
  },
  {
    "id": "TextAnimations/ScrambledText",
    "name": "ScrambledText",
    "category": "TextAnimations",
    "description": "Detects cursor position and applies a distortion effect to text.",
    "docsUrl": "https://reactbits.dev/text-animations/scrambled-text",
    "importPath": "./TextAnimations/ScrambledText/ScrambledText",
    "defaultProps": {
      "radius": 100,
      "duration": 1.2,
      "speed": 0.5,
      "scrambleChars": ".:"
    }
  },
  {
    "id": "TextAnimations/ScrollFloat",
    "name": "ScrollFloat",
    "category": "TextAnimations",
    "description": "Text gently floats / parallax shifts on scroll.",
    "docsUrl": "https://reactbits.dev/text-animations/scroll-float",
    "importPath": "./TextAnimations/ScrollFloat/ScrollFloat",
    "defaultProps": {
      "stagger": 0.03,
      "duration": 1
    }
  },
  {
    "id": "TextAnimations/ScrollReveal",
    "name": "ScrollReveal",
    "category": "TextAnimations",
    "description": "Text gently unblurs and reveals on scroll.",
    "docsUrl": "https://reactbits.dev/text-animations/scroll-reveal",
    "importPath": "./TextAnimations/ScrollReveal/ScrollReveal",
    "defaultProps": {
      "enableBlur": true,
      "baseOpacity": 0.1,
      "baseRotation": 3,
      "blurStrength": 4
    }
  },
  {
    "id": "TextAnimations/ScrollVelocity",
    "name": "ScrollVelocity",
    "category": "TextAnimations",
    "description": "",
    "docsUrl": "https://reactbits.dev/text-animations/scroll-velocity",
    "importPath": "./TextAnimations/ScrollVelocity/ScrollVelocity",
    "defaultProps": {
      "velocity": 100,
      "numCopies": 6,
      "damping": 50,
      "stiffness": 400
    }
  },
  {
    "id": "TextAnimations/ShinyText",
    "name": "ShinyText",
    "category": "TextAnimations",
    "description": "Metallic sheen sweeps across text producing a reflective highlight.",
    "docsUrl": "https://reactbits.dev/text-animations/shiny-text",
    "importPath": "./TextAnimations/ShinyText/ShinyText",
    "defaultProps": {
      "speed": 2,
      "delay": 0,
      "color": "#b5b5b5",
      "shineColor": "#ffffff",
      "spread": 120,
      "direction": "left",
      "yoyo": false,
      "pauseOnHover": false,
      "disabled": false
    }
  },
  {
    "id": "TextAnimations/Shuffle",
    "name": "Shuffle",
    "category": "TextAnimations",
    "description": "Animated text reveal where characters shuffle before settling.",
    "docsUrl": "https://reactbits.dev/text-animations/shuffle",
    "importPath": "./TextAnimations/Shuffle/Shuffle",
    "defaultProps": {
      "duration": 0.35,
      "shuffleTimes": 1,
      "stagger": 0.03,
      "shuffleDirection": "right",
      "ease": "power3.out",
      "loop": false,
      "loopDelay": 0,
      "triggerOnHover": true
    }
  },
  {
    "id": "TextAnimations/SplitText",
    "name": "SplitText",
    "category": "TextAnimations",
    "description": "Splits text into characters / words for staggered entrance animation.",
    "docsUrl": "https://reactbits.dev/text-animations/split-text",
    "importPath": "./TextAnimations/SplitText/SplitText",
    "defaultProps": {
      "text": "Hello, you!",
      "delay": 50,
      "duration": 1.25,
      "ease": "power3.out",
      "splitType": "chars",
      "showCallback": true
    }
  },
  {
    "id": "TextAnimations/TextCursor",
    "name": "TextCursor",
    "category": "TextAnimations",
    "description": "Make any text element follow your cursor, leaving a trail of copies behind it.",
    "docsUrl": "https://reactbits.dev/text-animations/text-cursor",
    "importPath": "./TextAnimations/TextCursor/TextCursor",
    "defaultProps": {
      "text": "⚛️",
      "followMouseDirection": true,
      "randomFloat": true
    }
  },
  {
    "id": "TextAnimations/TextPressure",
    "name": "TextPressure",
    "category": "TextAnimations",
    "description": "Characters scale / warp interactively based on pointer pressure zone.",
    "docsUrl": "https://reactbits.dev/text-animations/text-pressure",
    "importPath": "./TextAnimations/TextPressure/TextPressure",
    "defaultProps": {
      "text": "Hello!",
      "flex": true,
      "alpha": false,
      "stroke": false,
      "width": true,
      "weight": true,
      "italic": true,
      "textColor": "#ffffff",
      "strokeColor": "#5227FF"
    }
  },
  {
    "id": "TextAnimations/TextType",
    "name": "TextType",
    "category": "TextAnimations",
    "description": "Typewriter effect with blinking cursor and adjustable typing cadence.",
    "docsUrl": "https://reactbits.dev/text-animations/text-type",
    "importPath": "./TextAnimations/TextType/TextType",
    "defaultProps": {
      "texts": [
        "Welcome to React Bits! Good to see you!",
        "Build some amazing experiences!"
      ],
      "typingSpeed": 75,
      "pauseDuration": 1500,
      "deletingSpeed": 50,
      "showCursor": true,
      "cursorCharacter": "_",
      "variableSpeedEnabled": false,
      "variableSpeedMin": 60,
      "variableSpeedMax": 120,
      "cursorBlinkDuration": 0.5
    }
  },
  {
    "id": "TextAnimations/TrueFocus",
    "name": "TrueFocus",
    "category": "TextAnimations",
    "description": "Applies dynamic blur / clarity based over a series of words in order.",
    "docsUrl": "https://reactbits.dev/text-animations/true-focus",
    "importPath": "./TextAnimations/TrueFocus/TrueFocus",
    "defaultProps": {
      "manualMode": false,
      "blurAmount": 5,
      "animationDuration": 0.5,
      "pauseBetweenAnimations": 1,
      "borderColor": "#5227FF"
    }
  },
  {
    "id": "TextAnimations/VariableProximity",
    "name": "VariableProximity",
    "category": "TextAnimations",
    "description": "Letter styling changes continuously with pointer distance mapping.",
    "docsUrl": "https://reactbits.dev/text-animations/variable-proximity",
    "importPath": "./TextAnimations/VariableProximity/VariableProximity",
    "defaultProps": {
      "radius": 100,
      "falloff": "linear"
    }
  }
]

export const REACT_BITS_BY_ID = Object.fromEntries(
  REACT_BITS_CATALOG.map((entry) => [entry.id, entry]),
) as Record<string, ReactBitsCatalogEntry>

export const REACT_BITS_CATEGORIES = ["Animations","Backgrounds","Components","TextAnimations"] as const
