/** Compact Softree testimonial slider — section height, not full viewport */

export const SOFTREE_TESTIMONIAL_TOKENS = {
  colors: {
    bgCard: "var(--softree-bg-dark, #0a0a0a)",
    bgImageWrapper: "var(--softree-surface-1, #141414)",
    textEyebrowIcon: "var(--softree-accent, #ff7a2f)",
    textEyebrowLabel: "var(--softree-accent, #ff7a2f)",
    textQuoteDecorative: "rgba(255, 122, 47, 0.06)",
    textQuoteBody: "rgba(255, 255, 255, 0.92)",
    divider: "rgba(255, 255, 255, 0.08)",
    starFill: "var(--softree-accent, #ff7a2f)",
    starStroke: "var(--softree-accent, #ff7a2f)",
    textName: "rgba(255, 255, 255, 0.9)",
    textTitle: "rgba(255, 255, 255, 0.45)",
    textCounter: "rgba(255, 255, 255, 0.35)",
    bgButtonPrev: "rgba(255, 255, 255, 0.08)",
    bgButtonNext: "var(--softree-accent, #ff7a2f)",
    strokeButtonPrev: "rgba(255, 255, 255, 0.6)",
    strokeButtonNext: "#0a0a0a",
    bgProgressTrack: "rgba(255, 255, 255, 0.1)",
    bgProgressFill: "var(--softree-accent, #ff7a2f)",
    dotBg: "var(--softree-accent, #ff7a2f)",
    dotOpacityInactive: 0.35,
    dotOpacityActive: 1,
    imageGradient:
      "linear-gradient(145deg, rgba(10,10,10,0.15) 0%, rgba(10,10,10,0.55) 48%, rgba(10,10,10,0.88) 100%), linear-gradient(to top right, rgba(255,122,47,0.22) 0%, transparent 55%), linear-gradient(to bottom, transparent 25%, rgba(0,0,0,0.5) 100%)",
  },
  typography: {
    systemFont: "var(--font-sans)",
    quoteFont: "var(--font-sans)",
    eyebrowIcon: { fontSize: "10px" },
    eyebrowLabel: {
      fontSize: "10px",
      fontWeight: 600,
      letterSpacing: "0.16em",
      lineHeight: "1",
    },
    quoteDecorative: {
      fontSize: "96px",
      lineHeight: "1",
      fontFamily: "var(--font-sans)",
    },
    quoteBody: {
      fontSize: "clamp(1.0625rem, 2vw, 1.25rem)",
      fontWeight: 500,
      letterSpacing: "-0.02em",
      lineHeight: "1.45",
    },
    name: {
      fontSize: "13px",
      fontWeight: 600,
      letterSpacing: "-0.01em",
      lineHeight: "1.3",
    },
    title: {
      fontSize: "12px",
      fontWeight: 400,
      lineHeight: "1.35",
    },
    counter: {
      fontSize: "11px",
      fontWeight: 500,
      lineHeight: "1",
    },
  },
  spacing: {
    cardPaddingTop: 28,
    cardPaddingRight: 32,
    cardPaddingBottom: 28,
    cardPaddingLeft: 32,
    eyebrowGap: 6,
    eyebrowMarginBottom: 16,
    quoteHeight: 120,
    quoteDecorativeTop: -8,
    quoteDecorativeLeft: -4,
    dividerMarginTop: 16,
    dividerMarginBottom: 14,
    attributionGap: 10,
    starGap: 3,
    starMarginBottom: 6,
    nameTitleGap: 2,
    navButtonGap: 6,
    counterMarginRight: 2,
    counterMinWidth: 28,
    bottomProgressBottom: 0,
    bottomProgressInset: 12,
    bottomProgressHeight: 2,
    imagePanelMarginTop: 12,
    imagePanelMarginRight: 12,
    imagePanelMarginBottom: 12,
    imagePanelMarginLeft: 0,
    dotPaginationBottom: 12,
    dotPaginationGap: 4,
  },
  radius: {
    card: 16,
    navButton: 8,
    imagePanel: 12,
    dot: 999,
    progress: 999,
  },
  sizes: {
    leftPanelFlex: "1 1 52%",
    navButton: 36,
    navButtonSvg: 13,
    starSvg: 12,
    dotHeight: 5,
    dotInactiveWidth: 5,
    dotActiveWidth: 18,
    cardMinHeight: 340,
    imageMinHeight: 280,
  },
  animation: {
    slideDuration: 0.4,
    slideEase: [0.22, 1, 0.36, 1] as const,
    imageDuration: 0.45,
  },
} as const;
