import { createClient } from '@sanity/client';

const client = createClient({
  projectId: '1zmh4sfw',
  dataset: 'production',
  apiVersion: '2024-01-01',
  token: process.env.SANITY_API_TOKEN,
  useCdn: false,
});

const SITE = 'https://www.softreetechnology.com';

// Blog Posts Data — Real posts with images
const blogPosts = [
  {
    _type: 'post',
    title: 'Fix Your Customer Relations in 30 Days — The No-Fluff Plan',
    slug: { current: 'fix-customer-relations-30-days' },
    publishedAt: '2024-11-15T10:00:00.000Z',
    author: 'Nitin Dangwal',
    category: 'CRM',
    excerpt: 'Improve customer relations in 30 days with a simple, proven system. Learn why businesses lose customers, how to fix response times, build a single source of truth, and use CRM to drive loyalty and growth.',
    imageUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/test-clones/f9231059-3647-4f7a-ab8a-965fcb6abfb0-cynoteck-com/assets/images/1764661828137-Cyno_20Blog_20Card_20Image-16.jpg',
  },
  {
    _type: 'post',
    title: 'Dynamics 365 Integration: Streamlining Business Processes with Seamless Connectivity',
    slug: { current: 'dynamics-365-integration' },
    publishedAt: '2024-11-10T10:00:00.000Z',
    author: 'Abhishek Singh',
    category: 'Dynamics 365',
    excerpt: 'Microsoft Dynamics 365 integration made easy. Explore tools, APIs, best practices, and real use cases to connect systems for streamlined operations.',
    imageUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/test-clones/f9231059-3647-4f7a-ab8a-965fcb6abfb0-cynoteck-com/assets/images/1763372125827-Dynamics_20365_20Integration_20Strea-17.webp',
  },
  {
    _type: 'post',
    title: 'Importance of Customer Service in Healthcare: Why It Matters',
    slug: { current: 'healthcare-customer-service' },
    publishedAt: '2024-11-05T10:00:00.000Z',
    author: 'Abhishek Singh',
    category: 'Healthcare',
    excerpt: 'Customer service in healthcare matters. Discover tools, software, and strategies to improve patient experience, reduce wait times, and elevate care quality.',
    imageUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/test-clones/f9231059-3647-4f7a-ab8a-965fcb6abfb0-cynoteck-com/assets/images/1763112878004-Importance_20of_20Customer_20Service-18.webp',
  },
  {
    _type: 'post',
    title: 'What Is Salesforce and What Does It Really Do? A Complete Guide for Professionals',
    slug: { current: 'what-is-salesforce-complete-guide' },
    publishedAt: '2024-10-25T10:00:00.000Z',
    author: 'Nitin Dangwal',
    category: 'Salesforce',
    excerpt: 'Learn what Salesforce is, how it works, and why it\u2019s the world\u2019s #1 CRM. This guide explains features, benefits, and growth strategies for professionals.',
    imageUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/test-clones/f9231059-3647-4f7a-ab8a-965fcb6abfb0-cynoteck-com/assets/images/1763034508316-What_20is_20Salesforce_20and_20what_-19.webp',
  },
];

// Case Studies Data — All real case studies
const caseStudies = [
  // ============ AI ============
  {
    _type: 'caseStudy',
    title: 'AI-Powered E-Commerce Recommendation Engine',
    slug: { current: 'ai-ecommerce-recommendation-engine' },
    client: 'Retail Client',
    industry: 'AI Recommendation System',
    category: 'ai',
    date: '2024',
    description: 'A machine learning\u2013driven recommendation system that personalizes product discovery and boosts conversion rates.',
    imageUrl: `${SITE}/wp-content/uploads/2024/12/Shopping-E-Commerce.webp`,
    pdfUrl: `${SITE}/wp-content/uploads/2024/12/ShoppingEcommerce.pdf`,
    results: ['35% conversion uplift', 'Personalized at scale', 'Real-time inference'],
    color: '#FF5812',
    featured: true,
  },
  {
    _type: 'caseStudy',
    title: 'AI-Based Customer Support Automation',
    slug: { current: 'ai-customer-support-automation' },
    client: 'Pet Care Co.',
    industry: 'Generative AI',
    category: 'ai',
    date: '2024',
    description: 'An intelligent customer support system using LLM-powered chatbots and automated ticket routing.',
    imageUrl: `${SITE}/wp-content/uploads/2024/12/Pet-care.webp`,
    pdfUrl: `${SITE}/wp-content/uploads/2024/12/PET_CARE.pdf`,
    results: ['70% tickets auto-resolved', '24/7 availability', 'LLM-powered'],
    color: '#8B5CF6',
    featured: true,
  },
  {
    _type: 'caseStudy',
    title: 'Enterprise AI Decision Intelligence Platform',
    slug: { current: 'enterprise-ai-decision-intelligence' },
    client: 'Business Consultation App',
    industry: 'Enterprise AI',
    category: 'ai',
    date: '2024',
    description: 'An AI-driven analytics platform delivering predictive insights and real-time decision support.',
    imageUrl: `${SITE}/wp-content/uploads/2024/12/Business-Consultation-App.webp`,
    pdfUrl: `${SITE}/wp-content/uploads/2024/12/Business-Consultation-App-case-study-1.pdf`,
    results: ['Predictive insights', 'Real-time decisions', 'Enterprise-grade'],
    color: '#1852FF',
    featured: true,
  },
  {
    _type: 'caseStudy',
    title: 'AI Knowledge Assistant (RAG Architecture)',
    slug: { current: 'ai-knowledge-assistant-rag' },
    client: 'Internal Tools',
    industry: 'RAG & LLM',
    category: 'ai',
    date: '2024',
    description: 'A retrieval-augmented generation system enabling natural-language search across enterprise knowledge bases.',
    imageUrl: `${SITE}/wp-content/uploads/2024/11/Node.js-Express.js-HTML-editor.webp`,
    pdfUrl: `${SITE}/wp-content/uploads/2024/11/Public-Blogging-Website-Using-the-MERN-Stack.pdf`,
    results: ['Natural-language search', 'Enterprise KB', 'Cited responses'],
    color: '#10B981',
  },
  {
    _type: 'caseStudy',
    title: 'AI Marketing Intelligence Platform',
    slug: { current: 'ai-marketing-intelligence' },
    client: 'Food & Wine Brand',
    industry: 'AI Analytics',
    category: 'ai',
    date: '2024',
    description: 'An AI-powered platform that analyzes customer behavior and optimizes marketing campaigns automatically.',
    imageUrl: `${SITE}/wp-content/uploads/2024/11/FOOD-WINE-WEBSITE.webp`,
    pdfUrl: `${SITE}/wp-content/uploads/2024/11/FOOD-WINE-WEBSITE.pdf`,
    results: ['Auto-optimized campaigns', 'Behavioral insights', 'ROI uplift'],
    color: '#EC4899',
  },
  {
    _type: 'caseStudy',
    title: 'Predictive Maintenance AI System',
    slug: { current: 'predictive-maintenance-ai' },
    client: 'AutoRepair Pro',
    industry: 'Machine Learning',
    category: 'ai',
    date: '2024',
    description: 'A machine learning solution that predicts equipment failures and reduces downtime in industrial environments.',
    imageUrl: `${SITE}/wp-content/uploads/2024/11/AUTOREPAIR-PRO.webp`,
    pdfUrl: `${SITE}/wp-content/uploads/2024/11/AUTOREPAIR-PRO.pdf`,
    results: ['45% less downtime', 'Predictive alerts', 'Industrial IoT'],
    color: '#F59E0B',
  },
  {
    _type: 'caseStudy',
    title: 'AI-Driven Education Intelligence Platform',
    slug: { current: 'ai-education-intelligence' },
    client: 'EdTech',
    industry: 'AI for Education',
    category: 'ai',
    date: '2024',
    description: 'An AI-powered education platform delivering performance analytics and adaptive learning insights.',
    imageUrl: `${SITE}/wp-content/uploads/2024/11/EdTech-Management-Information-System.webp`,
    pdfUrl: `${SITE}/wp-content/uploads/2024/11/EdTech-Management-Information-System-.pdf`,
    results: ['Adaptive learning', 'Performance analytics', 'Personalized'],
    color: '#1852FF',
  },
  {
    _type: 'caseStudy',
    title: 'Healthcare AI Appointment Intelligence',
    slug: { current: 'healthcare-ai-appointment' },
    client: 'Healthcare Provider',
    industry: 'Healthcare AI',
    category: 'ai',
    date: '2024',
    description: 'An AI-enhanced scheduling system that predicts no-shows and optimizes appointment availability.',
    imageUrl: `${SITE}/wp-content/uploads/2024/11/LIVE-appointment-bookings-web.webp`,
    pdfUrl: `${SITE}/wp-content/uploads/2024/11/LIVE-appointment-bookings.docx.pdf`,
    results: ['No-show prediction', 'Optimized scheduling', 'Reduced wait times'],
    color: '#10B981',
  },

  // ============ WEB ============
  {
    _type: 'caseStudy',
    title: 'Shopping E-Commerce Platform',
    slug: { current: 'shopping-ecommerce-platform' },
    client: 'Retail Brand',
    industry: 'E-commerce',
    category: 'web',
    date: '2024',
    description: 'A scalable e-commerce web platform with product management, secure payments, and optimized checkout flow.',
    imageUrl: `${SITE}/wp-content/uploads/2024/12/Shopping-E-Commerce.webp`,
    pdfUrl: `${SITE}/wp-content/uploads/2024/12/ShoppingEcommerce.pdf`,
    challenge: 'The client needed a scalable online store capable of handling high traffic, secure transactions, and smooth product management.',
    solution: 'Built a high-performance e-commerce platform with optimized checkout flow, secure payment gateway integration, and advanced product management.',
    result: 'Increased conversion rates by 35%, improved checkout speed, and delivered seamless shopping across devices.',
    results: ['35% higher conversion', 'Secure payments', 'Optimized checkout'],
    color: '#FF5812',
    featured: true,
  },
  {
    _type: 'caseStudy',
    title: 'Pet Care Management Platform',
    slug: { current: 'pet-care-management' },
    client: 'Pet Services',
    industry: 'Service Platform',
    category: 'web',
    date: '2024',
    description: 'A web-based system for managing pet care services, bookings, and customer interactions.',
    imageUrl: `${SITE}/wp-content/uploads/2024/12/Pet-care.webp`,
    pdfUrl: `${SITE}/wp-content/uploads/2024/12/PET_CARE.pdf`,
    challenge: 'Manual appointment scheduling and fragmented customer records caused operational inefficiencies.',
    solution: 'Developed a centralized platform with online booking, customer management, and automated notifications.',
    result: 'Reduced booking errors by 50% and improved customer satisfaction.',
    results: ['50% fewer errors', 'Online booking', 'Auto notifications'],
    color: '#10B981',
  },
  {
    _type: 'caseStudy',
    title: 'Public Blogging Website (MERN Stack)',
    slug: { current: 'public-blogging-mern' },
    client: 'Media Platform',
    industry: 'Publishing',
    category: 'web',
    date: '2024',
    description: 'A full-stack blogging platform built with MERN stack supporting publishing, comments, and user authentication.',
    imageUrl: `${SITE}/wp-content/uploads/2024/11/Node.js-Express.js-HTML-editor.webp`,
    pdfUrl: `${SITE}/wp-content/uploads/2024/11/Public-Blogging-Website-Using-the-MERN-Stack.pdf`,
    results: ['JWT auth', 'Real-time updates', 'Scalable APIs'],
    color: '#1852FF',
  },
  {
    _type: 'caseStudy',
    title: 'Food & Wine Marketing Website',
    slug: { current: 'food-wine-website' },
    client: 'Food & Beverage Brand',
    industry: 'Marketing',
    category: 'web',
    date: '2024',
    description: 'A visually rich marketing website designed for food and beverage brands with content-focused UX.',
    imageUrl: `${SITE}/wp-content/uploads/2024/11/FOOD-WINE-WEBSITE.webp`,
    pdfUrl: `${SITE}/wp-content/uploads/2024/11/FOOD-WINE-WEBSITE.pdf`,
    results: ['Brand visibility', 'SEO optimized', 'Immersive UX'],
    color: '#EC4899',
  },

  // ============ POWER PLATFORM ============
  {
    _type: 'caseStudy',
    title: 'Barcode Scanner App',
    slug: { current: 'barcode-scanner-app' },
    client: 'Inventory Management',
    industry: 'Operations',
    category: 'power-platform',
    date: '2024',
    description: 'A Power Apps barcode scanner solution with real-time scanning and automated data capture for inventory.',
    imageUrl: '/images/case-study/power-apps/barcode.png',
    pdfUrl: '/pdf/Barcode Scanner App.pdf',
    challenge: 'Manual inventory tracking caused delays and frequent stock inaccuracies.',
    solution: 'Built a real-time barcode scanning Power App integrated with SharePoint and Dataverse.',
    result: 'Improved inventory accuracy and reduced stock processing time significantly.',
    results: ['Real-time scan', 'Dataverse integration', 'Reduced errors'],
    color: '#FF5812',
    featured: true,
  },
  {
    _type: 'caseStudy',
    title: 'ES Speaks & Travel Requests System',
    slug: { current: 'es-speaks-travel-requests' },
    client: 'Enterprise Client',
    industry: 'Internal Tools',
    category: 'power-platform',
    date: '2024',
    description: 'A Power Platform-based internal communication and travel request management application integrated with Teams.',
    imageUrl: '/images/case-study/power-apps/travel.png',
    pdfUrl: '/pdf/ES Speaks and Travel Requests Management System.pdf',
    results: ['Approval workflows', 'Teams integration', 'Centralized hub'],
    color: '#1852FF',
  },
  {
    _type: 'caseStudy',
    title: 'New Store Opening Process',
    slug: { current: 'new-store-opening' },
    client: 'Retail Chain',
    industry: 'Operations',
    category: 'power-platform',
    date: '2024',
    description: 'A centralized Power Platform solution to manage store setup tasks, approvals, vendor coordination, and progress tracking.',
    imageUrl: '/images/case-study/power-apps/store.png',
    pdfUrl: '/pdf/New Store Opening Process.pdf',
    results: ['Faster launches', 'Vendor coordination', 'Progress tracking'],
    color: '#10B981',
  },
  {
    _type: 'caseStudy',
    title: 'Project Portfolio Management',
    slug: { current: 'project-portfolio-management' },
    client: 'Enterprise PMO',
    industry: 'Project Management',
    category: 'power-platform',
    date: '2024',
    description: 'A portfolio management solution built on Microsoft Dataverse to centralize project tracking.',
    imageUrl: '/images/case-study/power-apps/project.avif',
    pdfUrl: `${SITE}/wp-content/uploads/2024/12/Projects-Portfolio-ManagementMicrosoft-Dataverse.pdf`,
    results: ['Dataverse-based', 'Dashboards', 'Milestone tracking'],
    color: '#8B5CF6',
  },

  // ============ SHAREPOINT ============
  {
    _type: 'caseStudy',
    title: 'Custom Copy & Move Panel for SharePoint Lists',
    slug: { current: 'sharepoint-copy-move-panel' },
    client: 'Enterprise SharePoint',
    industry: 'Microsoft 365',
    category: 'sharepoint',
    date: '2024',
    description: 'A custom SPFx solution built using Fluent UI to enable seamless copy and move operations for SharePoint list items.',
    imageUrl: '/images/case-study/sharepoint/copy.png',
    pdfUrl: `${SITE}/wp-content/uploads/2025/03/Enhancing-SharePoint-List-Management-with-a-Custom-Copy-Move-Panel-Using-SPFx-and-Fluent-UI.pdf`,
    challenge: 'Manual list item transfers caused inefficiencies and data duplication.',
    solution: 'Built a custom SPFx panel with structured copy/move logic and metadata retention.',
    result: 'Improved list management efficiency and reduced manual errors.',
    results: ['SPFx + Fluent UI', 'Metadata retention', 'Faster transfers'],
    color: '#1852FF',
  },
  {
    _type: 'caseStudy',
    title: 'Enable & Disable MFA Using PowerShell',
    slug: { current: 'mfa-powershell-automation' },
    client: 'M365 Admins',
    industry: 'Security Automation',
    category: 'sharepoint',
    date: '2024',
    description: 'A PowerShell automation approach to manage Multi-Factor Authentication (MFA) settings for Microsoft 365 users securely.',
    imageUrl: '/images/case-study/sharepoint/mfa.png',
    pdfUrl: `${SITE}/wp-content/uploads/2024/11/How-To-Enable-And-Disable-MFA-Using-PowerShell-1.pdf`,
    results: ['Bulk MFA control', 'Admin efficiency', 'Security compliance'],
    color: '#FF5812',
  },
  {
    _type: 'caseStudy',
    title: 'Dynamic Navigation Bar Using SPFx',
    slug: { current: 'spfx-dynamic-navigation' },
    client: 'Enterprise Client',
    industry: 'SharePoint UX',
    category: 'sharepoint',
    date: '2024',
    description: 'An SPFx Application Customizer that delivers a dynamic, role-based navigation bar across modern SharePoint sites.',
    imageUrl: '/images/case-study/sharepoint/dynamic.png',
    pdfUrl: `${SITE}/wp-content/uploads/2024/12/Creating-a-Dynamic-Navigation-Bar-using-SPFx-Application-Customizer.pdf`,
    results: ['Role-based nav', 'Cross-site consistency', 'Modern UX'],
    color: '#10B981',
  },
  {
    _type: 'caseStudy',
    title: 'Custom Footer for SharePoint Online',
    slug: { current: 'sharepoint-custom-footer' },
    client: 'Enterprise Brand',
    industry: 'SharePoint UX',
    category: 'sharepoint',
    date: '2024',
    description: 'A reusable SPFx footer component designed to enhance branding and accessibility.',
    imageUrl: '/images/case-study/sharepoint/footer.png',
    pdfUrl: `${SITE}/wp-content/uploads/2024/12/Enhancing-User-Experience-with-a-Custom-Footer-using-SPFx.pdf`,
    results: ['Reusable extension', 'Centralized config', 'Branding parity'],
    color: '#8B5CF6',
  },
  {
    _type: 'caseStudy',
    title: 'Global Notification Banner in SharePoint',
    slug: { current: 'sharepoint-notification-banner' },
    client: 'Enterprise Comms',
    industry: 'Internal Comms',
    category: 'sharepoint',
    date: '2024',
    description: 'A SharePoint-wide notification banner using SPFx Application Customizer for urgent updates.',
    imageUrl: '/images/case-study/sharepoint/global.png',
    pdfUrl: `${SITE}/wp-content/uploads/2024/12/Implementing-a-Global-Notification-Banner-with-SPFx-Application-Customizer.pdf`,
    results: ['Centralized banner', 'Configurable messaging', 'Tenant-wide'],
    color: '#F59E0B',
  },

  // ============ MOBILE ============
  {
    _type: 'caseStudy',
    title: 'Doctor Appointment System',
    slug: { current: 'doctor-appointment-system' },
    client: 'Healthcare Clinic',
    industry: 'Healthcare App',
    category: 'mobile',
    date: '2024',
    description: 'A mobile application enabling patients to book appointments, manage schedules, and receive real-time notifications.',
    imageUrl: '/images/case-study/mobile/doctor.png',
    pdfUrl: `${SITE}/wp-content/uploads/2024/11/Building-a-Doctor-Appointment-Booking-System-with-React.pdf`,
    challenge: 'Manual scheduling, limited doctor availability visibility, and lack of automated reminders.',
    solution: 'Responsive mobile app with real-time scheduling, calendar integration, push notifications, and admin dashboard.',
    result: 'Reduced booking time by 60%, improved patient engagement, and streamlined clinic operations.',
    results: ['60% faster booking', 'Push notifications', 'Admin dashboard'],
    color: '#10B981',
    featured: true,
  },
  {
    _type: 'caseStudy',
    title: 'Education App Backend',
    slug: { current: 'education-app-backend' },
    client: 'EdTech Platform',
    industry: 'Education App',
    category: 'mobile',
    date: '2024',
    description: 'A scalable backend system powering mobile education platforms with secure APIs and real-time data access.',
    imageUrl: '/images/case-study/mobile/education.png',
    pdfUrl: `${SITE}/wp-content/uploads/2024/11/Behind-the-Scenes-of-E.pdf`,
    results: ['Scalable APIs', 'RBAC', 'Concurrent users'],
    color: '#1852FF',
  },
  {
    _type: 'caseStudy',
    title: 'Movie Ticket Booking App',
    slug: { current: 'movie-ticket-booking-app' },
    client: 'Entertainment',
    industry: 'Entertainment App',
    category: 'mobile',
    date: '2024',
    description: 'A mobile ticket booking application with seat selection, payment processing, and booking confirmation.',
    imageUrl: '/images/case-study/mobile/movie.png',
    pdfUrl: `${SITE}/wp-content/uploads/2024/11/Movie-Ticket-Booking-App-Backend-Documentation.pdf`,
    results: ['Real-time seats', 'Payment integration', 'Booking confirmations'],
    color: '#EC4899',
  },
  {
    _type: 'caseStudy',
    title: 'Education Mobile App',
    slug: { current: 'education-mobile-app' },
    client: 'EdTech',
    industry: 'Education App',
    category: 'mobile',
    date: '2024',
    description: 'A student-focused mobile application providing access to courses, learning material, and assessments.',
    imageUrl: '/images/case-study/mobile/education.png',
    pdfUrl: `${SITE}/wp-content/uploads/2024/09/Education-App.pdf`,
    results: ['Interactive content', 'Assessment tracking', 'Personalized'],
    color: '#8B5CF6',
  },
];

async function wipeExisting() {
  console.log('\u{1F9F9} Wiping existing posts and case studies...');
  await client.delete({ query: '*[_type == "post"]' });
  await client.delete({ query: '*[_type == "caseStudy"]' });
  console.log('\u2705 Wiped.\n');
}

async function seedContent() {
  console.log('\u{1F331} Seeding Sanity content...\n');
  console.log('(Old fake data may remain — delete it manually in Studio if needed)\n');

  console.log('\u{1F4F0} Creating blog posts...');
  for (const post of blogPosts) {
    try {
      const doc = await client.create(post as any);
      console.log(`\u2705 Created blog post: ${doc.title}`);
    } catch (error) {
      console.error(`\u274C Failed: ${post.title}`, error);
    }
  }

  console.log('\n\u{1F4CA} Creating case studies...');
  for (const study of caseStudies) {
    try {
      const doc = await client.create(study as any);
      console.log(`\u2705 Created case study: ${doc.title}`);
    } catch (error) {
      console.error(`\u274C Failed: ${study.title}`, error);
    }
  }

  console.log(`\n\u2728 Done! ${blogPosts.length} posts + ${caseStudies.length} case studies`);
}

// Run the seed function
seedContent().catch(console.error);
